/**
 * Project Name:welink-biz
 * File Name:MikuAgencyShareAccountModel.java
 * Package Name:com.welink.biz.common.model
 * Date:2015年11月4日下午5:01:52
 * Copyright (c) 2015, chenzhou1025@126.com All Rights Reserved.
 *
*/

package com.welink.commons.vo;

import java.util.Date;

/**
 * ClassName:MikuAgencyShareAccountModel <br/>
 * Function: TODO ADD FUNCTION. <br/>
 * Reason:	 TODO ADD REASON. <br/>
 * Date:     2015年11月4日 下午5:01:52 <br/>
 * @author   LuoGuangChun
 * @version  
 * @since    JDK 1.6
 * @see 	 
 */
public class MikuAgencyShareAccountVO {
	private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miku_agency_share_account.agency_id
     *
     * @mbggenerated Wed Nov 04 16:43:00 CST 2015
     */
    private Long agencyId;
    
    private String mobile;
    
    private String nickName;
    
    private String profilePic; //用户头像
    
    private Byte isAgency;
    
    private Integer contactsLevel;	//人脉等级 

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miku_agency_share_account.total_share_fee
     *
     * @mbggenerated Wed Nov 04 16:43:00 CST 2015
     */
    private String totalShareFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miku_agency_share_account.total_gotpay_fee
     *
     * @mbggenerated Wed Nov 04 16:43:00 CST 2015
     */
    private String totalGotpayFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miku_agency_share_account.no_getpay_fee
     *
     * @mbggenerated Wed Nov 04 16:43:00 CST 2015
     */
    private String noGetpayFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miku_agency_share_account.getpaying_fee
     *
     * @mbggenerated Wed Nov 04 16:43:00 CST 2015
     */
    private String getpayingFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miku_agency_share_account.direct_sales_fee
     *
     * @mbggenerated Wed Nov 04 16:43:00 CST 2015
     */
    private String directSalesFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miku_agency_share_account.direct_share_fee
     *
     * @mbggenerated Wed Nov 04 16:43:00 CST 2015
     */
    private String directShareFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miku_agency_share_account.indirect_sales_fee
     *
     * @mbggenerated Wed Nov 04 16:43:00 CST 2015
     */
    private String indirectSalesFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miku_agency_share_account.indirect_share_fee
     *
     * @mbggenerated Wed Nov 04 16:43:00 CST 2015
     */
    private String indirectShareFee;
    
    private String canGetpayFee;	//可提现金额
    
    private Long pTradesCount;		//订单数
    
    private String pSalesFee;			//销售额
    
    private String pOfferFee;			//贡献分润
    
    private Date dateCreated;		//用户创建时间

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Long getAgencyId() {
		return agencyId;
	}

	public void setAgencyId(Long agencyId) {
		this.agencyId = agencyId;
	}

	public String getNickName() {
		return nickName;
	}

	public void setNickName(String nickName) {
		this.nickName = nickName;
	}

	public String getProfilePic() {
		return profilePic;
	}

	public void setProfilePic(String profilePic) {
		this.profilePic = profilePic;
	}

	public String getTotalShareFee() {
		return totalShareFee;
	}

	public void setTotalShareFee(String totalShareFee) {
		this.totalShareFee = totalShareFee;
	}

	public String getTotalGotpayFee() {
		return totalGotpayFee;
	}

	public void setTotalGotpayFee(String totalGotpayFee) {
		this.totalGotpayFee = totalGotpayFee;
	}

	public String getNoGetpayFee() {
		return noGetpayFee;
	}

	public void setNoGetpayFee(String noGetpayFee) {
		this.noGetpayFee = noGetpayFee;
	}

	public String getGetpayingFee() {
		return getpayingFee;
	}

	public void setGetpayingFee(String getpayingFee) {
		this.getpayingFee = getpayingFee;
	}

	public String getDirectSalesFee() {
		return directSalesFee;
	}

	public void setDirectSalesFee(String directSalesFee) {
		this.directSalesFee = directSalesFee;
	}

	public String getDirectShareFee() {
		return directShareFee;
	}

	public void setDirectShareFee(String directShareFee) {
		this.directShareFee = directShareFee;
	}

	public String getIndirectSalesFee() {
		return indirectSalesFee;
	}

	public void setIndirectSalesFee(String indirectSalesFee) {
		this.indirectSalesFee = indirectSalesFee;
	}

	public String getIndirectShareFee() {
		return indirectShareFee;
	}

	public void setIndirectShareFee(String indirectShareFee) {
		this.indirectShareFee = indirectShareFee;
	}

	public Long getpTradesCount() {
		return pTradesCount;
	}

	public void setpTradesCount(Long pTradesCount) {
		this.pTradesCount = pTradesCount;
	}

	public String getpSalesFee() {
		return pSalesFee;
	}

	public void setpSalesFee(String pSalesFee) {
		this.pSalesFee = pSalesFee;
	}

	public String getpOfferFee() {
		return pOfferFee;
	}

	public void setpOfferFee(String pOfferFee) {
		this.pOfferFee = pOfferFee;
	}

	public Date getDateCreated() {
		return dateCreated;
	}

	public void setDateCreated(Date dateCreated) {
		this.dateCreated = dateCreated;
	}

	public String getMobile() {
		return mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	public Byte getIsAgency() {
		return isAgency;
	}

	public void setIsAgency(Byte isAgency) {
		this.isAgency = isAgency;
	}

	public String getCanGetpayFee() {
		return canGetpayFee;
	}

	public void setCanGetpayFee(String canGetpayFee) {
		this.canGetpayFee = canGetpayFee;
	}

	public Integer getContactsLevel() {
		return contactsLevel;
	}

	public void setContactsLevel(Integer contactsLevel) {
		this.contactsLevel = contactsLevel;
	}
    
    
}

