package com.welink.biz.common.model;


public class MikuCrowdfundDetailVO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miku_crowdfund_detail.id
     *
     * @mbggenerated Mon Feb 15 15:58:29 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miku_crowdfund_detail.crowdfund_id
     *
     * @mbggenerated Mon Feb 15 15:58:29 CST 2016
     */
    private Long crowdfundId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miku_crowdfund_detail.item_id
     *
     * @mbggenerated Mon Feb 15 15:58:29 CST 2016
     */
    private Long itemId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miku_crowdfund_detail.sold_num
     *
     * @mbggenerated Mon Feb 15 15:58:29 CST 2016
     */
    private Integer soldNum;
    
    private String returnContent;

    private String riskTips;

    private String specialNote;

    /*private Long version;
    private Date dateCreated;
    private Date lastUpdated;*/
    
    private ItemViewDO itemViewDO;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miku_crowdfund_detail.id
     *
     * @return the value of miku_crowdfund_detail.id
     *
     * @mbggenerated Mon Feb 15 15:58:29 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miku_crowdfund_detail.id
     *
     * @param id the value for miku_crowdfund_detail.id
     *
     * @mbggenerated Mon Feb 15 15:58:29 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miku_crowdfund_detail.crowdfund_id
     *
     * @return the value of miku_crowdfund_detail.crowdfund_id
     *
     * @mbggenerated Mon Feb 15 15:58:29 CST 2016
     */
    public Long getCrowdfundId() {
        return crowdfundId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miku_crowdfund_detail.crowdfund_id
     *
     * @param crowdfundId the value for miku_crowdfund_detail.crowdfund_id
     *
     * @mbggenerated Mon Feb 15 15:58:29 CST 2016
     */
    public void setCrowdfundId(Long crowdfundId) {
        this.crowdfundId = crowdfundId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miku_crowdfund_detail.item_id
     *
     * @return the value of miku_crowdfund_detail.item_id
     *
     * @mbggenerated Mon Feb 15 15:58:29 CST 2016
     */
    public Long getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miku_crowdfund_detail.item_id
     *
     * @param itemId the value for miku_crowdfund_detail.item_id
     *
     * @mbggenerated Mon Feb 15 15:58:29 CST 2016
     */
    public void setItemId(Long itemId) {
        this.itemId = itemId;
    }

	public Integer getSoldNum() {
		return soldNum;
	}

	public void setSoldNum(Integer soldNum) {
		this.soldNum = soldNum;
	}

	public ItemViewDO getItemViewDO() {
		return itemViewDO;
	}

	public void setItemViewDO(ItemViewDO itemViewDO) {
		this.itemViewDO = itemViewDO;
	}

	public String getReturnContent() {
		return returnContent;
	}

	public void setReturnContent(String returnContent) {
		this.returnContent = returnContent;
	}

	public String getRiskTips() {
		return riskTips;
	}

	public void setRiskTips(String riskTips) {
		this.riskTips = riskTips;
	}

	public String getSpecialNote() {
		return specialNote;
	}

	public void setSpecialNote(String specialNote) {
		this.specialNote = specialNote;
	}
}