package com.welink.commons.domain;

import java.util.Date;

public class InstallActiveDO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column install_active.id
     *
     * @mbggenerated Tue Apr 07 18:07:58 CST 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column install_active.item_id
     *
     * @mbggenerated Tue Apr 07 18:07:58 CST 2015
     */
    private Long itemId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column install_active.category_id
     *
     * @mbggenerated Tue Apr 07 18:07:58 CST 2015
     */
    private Long categoryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column install_active.buyer_id
     *
     * @mbggenerated Tue Apr 07 18:07:58 CST 2015
     */
    private Long buyerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column install_active.mobile
     *
     * @mbggenerated Tue Apr 07 18:07:58 CST 2015
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column install_active.date_created
     *
     * @mbggenerated Tue Apr 07 18:07:58 CST 2015
     */
    private Date dateCreated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column install_active.last_updated
     *
     * @mbggenerated Tue Apr 07 18:07:58 CST 2015
     */
    private Date lastUpdated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column install_active.count
     *
     * @mbggenerated Tue Apr 07 18:07:58 CST 2015
     */
    private Integer count;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column install_active.base_item_id
     *
     * @mbggenerated Tue Apr 07 18:07:58 CST 2015
     */
    private Long baseItemId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column install_active.trade_id
     *
     * @mbggenerated Tue Apr 07 18:07:58 CST 2015
     */
    private Long tradeId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column install_active.id
     *
     * @return the value of install_active.id
     * @mbggenerated Tue Apr 07 18:07:58 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column install_active.id
     *
     * @param id the value for install_active.id
     * @mbggenerated Tue Apr 07 18:07:58 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column install_active.item_id
     *
     * @return the value of install_active.item_id
     * @mbggenerated Tue Apr 07 18:07:58 CST 2015
     */
    public Long getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column install_active.item_id
     *
     * @param itemId the value for install_active.item_id
     * @mbggenerated Tue Apr 07 18:07:58 CST 2015
     */
    public void setItemId(Long itemId) {
        this.itemId = itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column install_active.category_id
     *
     * @return the value of install_active.category_id
     * @mbggenerated Tue Apr 07 18:07:58 CST 2015
     */
    public Long getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column install_active.category_id
     *
     * @param categoryId the value for install_active.category_id
     * @mbggenerated Tue Apr 07 18:07:58 CST 2015
     */
    public void setCategoryId(Long categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column install_active.buyer_id
     *
     * @return the value of install_active.buyer_id
     * @mbggenerated Tue Apr 07 18:07:58 CST 2015
     */
    public Long getBuyerId() {
        return buyerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column install_active.buyer_id
     *
     * @param buyerId the value for install_active.buyer_id
     * @mbggenerated Tue Apr 07 18:07:58 CST 2015
     */
    public void setBuyerId(Long buyerId) {
        this.buyerId = buyerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column install_active.mobile
     *
     * @return the value of install_active.mobile
     * @mbggenerated Tue Apr 07 18:07:58 CST 2015
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column install_active.mobile
     *
     * @param mobile the value for install_active.mobile
     * @mbggenerated Tue Apr 07 18:07:58 CST 2015
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column install_active.date_created
     *
     * @return the value of install_active.date_created
     * @mbggenerated Tue Apr 07 18:07:58 CST 2015
     */
    public Date getDateCreated() {
        return dateCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column install_active.date_created
     *
     * @param dateCreated the value for install_active.date_created
     * @mbggenerated Tue Apr 07 18:07:58 CST 2015
     */
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column install_active.last_updated
     *
     * @return the value of install_active.last_updated
     * @mbggenerated Tue Apr 07 18:07:58 CST 2015
     */
    public Date getLastUpdated() {
        return lastUpdated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column install_active.last_updated
     *
     * @param lastUpdated the value for install_active.last_updated
     * @mbggenerated Tue Apr 07 18:07:58 CST 2015
     */
    public void setLastUpdated(Date lastUpdated) {
        this.lastUpdated = lastUpdated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column install_active.count
     *
     * @return the value of install_active.count
     * @mbggenerated Tue Apr 07 18:07:58 CST 2015
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column install_active.count
     *
     * @param count the value for install_active.count
     * @mbggenerated Tue Apr 07 18:07:58 CST 2015
     */
    public void setCount(Integer count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column install_active.base_item_id
     *
     * @return the value of install_active.base_item_id
     * @mbggenerated Tue Apr 07 18:07:58 CST 2015
     */
    public Long getBaseItemId() {
        return baseItemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column install_active.base_item_id
     *
     * @param baseItemId the value for install_active.base_item_id
     * @mbggenerated Tue Apr 07 18:07:58 CST 2015
     */
    public void setBaseItemId(Long baseItemId) {
        this.baseItemId = baseItemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column install_active.trade_id
     *
     * @return the value of install_active.trade_id
     * @mbggenerated Tue Apr 07 18:07:58 CST 2015
     */
    public Long getTradeId() {
        return tradeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column install_active.trade_id
     *
     * @param tradeId the value for install_active.trade_id
     * @mbggenerated Tue Apr 07 18:07:58 CST 2015
     */
    public void setTradeId(Long tradeId) {
        this.tradeId = tradeId;
    }
}