package com.welink.commons.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class MikuMineCourseStepDOExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table miku_mine_course_step
     *
     * @mbggenerated Sat May 21 16:59:55 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table miku_mine_course_step
     *
     * @mbggenerated Sat May 21 16:59:55 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table miku_mine_course_step
     *
     * @mbggenerated Sat May 21 16:59:55 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table miku_mine_course_step
     *
     * @mbggenerated Sat May 21 16:59:55 CST 2016
     */
    protected Integer offset;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table miku_mine_course_step
     *
     * @mbggenerated Sat May 21 16:59:55 CST 2016
     */
    protected Integer limit;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miku_mine_course_step
     *
     * @mbggenerated Sat May 21 16:59:55 CST 2016
     */
    public MikuMineCourseStepDOExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miku_mine_course_step
     *
     * @mbggenerated Sat May 21 16:59:55 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miku_mine_course_step
     *
     * @mbggenerated Sat May 21 16:59:55 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miku_mine_course_step
     *
     * @mbggenerated Sat May 21 16:59:55 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miku_mine_course_step
     *
     * @mbggenerated Sat May 21 16:59:55 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miku_mine_course_step
     *
     * @mbggenerated Sat May 21 16:59:55 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miku_mine_course_step
     *
     * @mbggenerated Sat May 21 16:59:55 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miku_mine_course_step
     *
     * @mbggenerated Sat May 21 16:59:55 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miku_mine_course_step
     *
     * @mbggenerated Sat May 21 16:59:55 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miku_mine_course_step
     *
     * @mbggenerated Sat May 21 16:59:55 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miku_mine_course_step
     *
     * @mbggenerated Sat May 21 16:59:55 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miku_mine_course_step
     *
     * @mbggenerated Sat May 21 16:59:55 CST 2016
     */
    public void setOffset(Integer offset) {
        this.offset=offset;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miku_mine_course_step
     *
     * @mbggenerated Sat May 21 16:59:55 CST 2016
     */
    public Integer getOffset() {
        return offset;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miku_mine_course_step
     *
     * @mbggenerated Sat May 21 16:59:55 CST 2016
     */
    public void setLimit(Integer limit) {
        this.limit=limit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miku_mine_course_step
     *
     * @mbggenerated Sat May 21 16:59:55 CST 2016
     */
    public Integer getLimit() {
        return limit;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table miku_mine_course_step
     *
     * @mbggenerated Sat May 21 16:59:55 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andCourseIdIsNull() {
            addCriterion("course_id is null");
            return (Criteria) this;
        }

        public Criteria andCourseIdIsNotNull() {
            addCriterion("course_id is not null");
            return (Criteria) this;
        }

        public Criteria andCourseIdEqualTo(Long value) {
            addCriterion("course_id =", value, "courseId");
            return (Criteria) this;
        }

        public Criteria andCourseIdNotEqualTo(Long value) {
            addCriterion("course_id <>", value, "courseId");
            return (Criteria) this;
        }

        public Criteria andCourseIdGreaterThan(Long value) {
            addCriterion("course_id >", value, "courseId");
            return (Criteria) this;
        }

        public Criteria andCourseIdGreaterThanOrEqualTo(Long value) {
            addCriterion("course_id >=", value, "courseId");
            return (Criteria) this;
        }

        public Criteria andCourseIdLessThan(Long value) {
            addCriterion("course_id <", value, "courseId");
            return (Criteria) this;
        }

        public Criteria andCourseIdLessThanOrEqualTo(Long value) {
            addCriterion("course_id <=", value, "courseId");
            return (Criteria) this;
        }

        public Criteria andCourseIdIn(List<Long> values) {
            addCriterion("course_id in", values, "courseId");
            return (Criteria) this;
        }

        public Criteria andCourseIdNotIn(List<Long> values) {
            addCriterion("course_id not in", values, "courseId");
            return (Criteria) this;
        }

        public Criteria andCourseIdBetween(Long value1, Long value2) {
            addCriterion("course_id between", value1, value2, "courseId");
            return (Criteria) this;
        }

        public Criteria andCourseIdNotBetween(Long value1, Long value2) {
            addCriterion("course_id not between", value1, value2, "courseId");
            return (Criteria) this;
        }

        public Criteria andStepNameIsNull() {
            addCriterion("step_name is null");
            return (Criteria) this;
        }

        public Criteria andStepNameIsNotNull() {
            addCriterion("step_name is not null");
            return (Criteria) this;
        }

        public Criteria andStepNameEqualTo(String value) {
            addCriterion("step_name =", value, "stepName");
            return (Criteria) this;
        }

        public Criteria andStepNameNotEqualTo(String value) {
            addCriterion("step_name <>", value, "stepName");
            return (Criteria) this;
        }

        public Criteria andStepNameGreaterThan(String value) {
            addCriterion("step_name >", value, "stepName");
            return (Criteria) this;
        }

        public Criteria andStepNameGreaterThanOrEqualTo(String value) {
            addCriterion("step_name >=", value, "stepName");
            return (Criteria) this;
        }

        public Criteria andStepNameLessThan(String value) {
            addCriterion("step_name <", value, "stepName");
            return (Criteria) this;
        }

        public Criteria andStepNameLessThanOrEqualTo(String value) {
            addCriterion("step_name <=", value, "stepName");
            return (Criteria) this;
        }

        public Criteria andStepNameLike(String value) {
            addCriterion("step_name like", value, "stepName");
            return (Criteria) this;
        }

        public Criteria andStepNameNotLike(String value) {
            addCriterion("step_name not like", value, "stepName");
            return (Criteria) this;
        }

        public Criteria andStepNameIn(List<String> values) {
            addCriterion("step_name in", values, "stepName");
            return (Criteria) this;
        }

        public Criteria andStepNameNotIn(List<String> values) {
            addCriterion("step_name not in", values, "stepName");
            return (Criteria) this;
        }

        public Criteria andStepNameBetween(String value1, String value2) {
            addCriterion("step_name between", value1, value2, "stepName");
            return (Criteria) this;
        }

        public Criteria andStepNameNotBetween(String value1, String value2) {
            addCriterion("step_name not between", value1, value2, "stepName");
            return (Criteria) this;
        }

        public Criteria andStepShortNameIsNull() {
            addCriterion("step_short_name is null");
            return (Criteria) this;
        }

        public Criteria andStepShortNameIsNotNull() {
            addCriterion("step_short_name is not null");
            return (Criteria) this;
        }

        public Criteria andStepShortNameEqualTo(String value) {
            addCriterion("step_short_name =", value, "stepShortName");
            return (Criteria) this;
        }

        public Criteria andStepShortNameNotEqualTo(String value) {
            addCriterion("step_short_name <>", value, "stepShortName");
            return (Criteria) this;
        }

        public Criteria andStepShortNameGreaterThan(String value) {
            addCriterion("step_short_name >", value, "stepShortName");
            return (Criteria) this;
        }

        public Criteria andStepShortNameGreaterThanOrEqualTo(String value) {
            addCriterion("step_short_name >=", value, "stepShortName");
            return (Criteria) this;
        }

        public Criteria andStepShortNameLessThan(String value) {
            addCriterion("step_short_name <", value, "stepShortName");
            return (Criteria) this;
        }

        public Criteria andStepShortNameLessThanOrEqualTo(String value) {
            addCriterion("step_short_name <=", value, "stepShortName");
            return (Criteria) this;
        }

        public Criteria andStepShortNameLike(String value) {
            addCriterion("step_short_name like", value, "stepShortName");
            return (Criteria) this;
        }

        public Criteria andStepShortNameNotLike(String value) {
            addCriterion("step_short_name not like", value, "stepShortName");
            return (Criteria) this;
        }

        public Criteria andStepShortNameIn(List<String> values) {
            addCriterion("step_short_name in", values, "stepShortName");
            return (Criteria) this;
        }

        public Criteria andStepShortNameNotIn(List<String> values) {
            addCriterion("step_short_name not in", values, "stepShortName");
            return (Criteria) this;
        }

        public Criteria andStepShortNameBetween(String value1, String value2) {
            addCriterion("step_short_name between", value1, value2, "stepShortName");
            return (Criteria) this;
        }

        public Criteria andStepShortNameNotBetween(String value1, String value2) {
            addCriterion("step_short_name not between", value1, value2, "stepShortName");
            return (Criteria) this;
        }

        public Criteria andStepOrderIsNull() {
            addCriterion("step_order is null");
            return (Criteria) this;
        }

        public Criteria andStepOrderIsNotNull() {
            addCriterion("step_order is not null");
            return (Criteria) this;
        }

        public Criteria andStepOrderEqualTo(Integer value) {
            addCriterion("step_order =", value, "stepOrder");
            return (Criteria) this;
        }

        public Criteria andStepOrderNotEqualTo(Integer value) {
            addCriterion("step_order <>", value, "stepOrder");
            return (Criteria) this;
        }

        public Criteria andStepOrderGreaterThan(Integer value) {
            addCriterion("step_order >", value, "stepOrder");
            return (Criteria) this;
        }

        public Criteria andStepOrderGreaterThanOrEqualTo(Integer value) {
            addCriterion("step_order >=", value, "stepOrder");
            return (Criteria) this;
        }

        public Criteria andStepOrderLessThan(Integer value) {
            addCriterion("step_order <", value, "stepOrder");
            return (Criteria) this;
        }

        public Criteria andStepOrderLessThanOrEqualTo(Integer value) {
            addCriterion("step_order <=", value, "stepOrder");
            return (Criteria) this;
        }

        public Criteria andStepOrderIn(List<Integer> values) {
            addCriterion("step_order in", values, "stepOrder");
            return (Criteria) this;
        }

        public Criteria andStepOrderNotIn(List<Integer> values) {
            addCriterion("step_order not in", values, "stepOrder");
            return (Criteria) this;
        }

        public Criteria andStepOrderBetween(Integer value1, Integer value2) {
            addCriterion("step_order between", value1, value2, "stepOrder");
            return (Criteria) this;
        }

        public Criteria andStepOrderNotBetween(Integer value1, Integer value2) {
            addCriterion("step_order not between", value1, value2, "stepOrder");
            return (Criteria) this;
        }

        public Criteria andStepTypeIsNull() {
            addCriterion("step_type is null");
            return (Criteria) this;
        }

        public Criteria andStepTypeIsNotNull() {
            addCriterion("step_type is not null");
            return (Criteria) this;
        }

        public Criteria andStepTypeEqualTo(Byte value) {
            addCriterion("step_type =", value, "stepType");
            return (Criteria) this;
        }

        public Criteria andStepTypeNotEqualTo(Byte value) {
            addCriterion("step_type <>", value, "stepType");
            return (Criteria) this;
        }

        public Criteria andStepTypeGreaterThan(Byte value) {
            addCriterion("step_type >", value, "stepType");
            return (Criteria) this;
        }

        public Criteria andStepTypeGreaterThanOrEqualTo(Byte value) {
            addCriterion("step_type >=", value, "stepType");
            return (Criteria) this;
        }

        public Criteria andStepTypeLessThan(Byte value) {
            addCriterion("step_type <", value, "stepType");
            return (Criteria) this;
        }

        public Criteria andStepTypeLessThanOrEqualTo(Byte value) {
            addCriterion("step_type <=", value, "stepType");
            return (Criteria) this;
        }

        public Criteria andStepTypeIn(List<Byte> values) {
            addCriterion("step_type in", values, "stepType");
            return (Criteria) this;
        }

        public Criteria andStepTypeNotIn(List<Byte> values) {
            addCriterion("step_type not in", values, "stepType");
            return (Criteria) this;
        }

        public Criteria andStepTypeBetween(Byte value1, Byte value2) {
            addCriterion("step_type between", value1, value2, "stepType");
            return (Criteria) this;
        }

        public Criteria andStepTypeNotBetween(Byte value1, Byte value2) {
            addCriterion("step_type not between", value1, value2, "stepType");
            return (Criteria) this;
        }

        public Criteria andStepIntervalIsNull() {
            addCriterion("step_interval is null");
            return (Criteria) this;
        }

        public Criteria andStepIntervalIsNotNull() {
            addCriterion("step_interval is not null");
            return (Criteria) this;
        }

        public Criteria andStepIntervalEqualTo(Integer value) {
            addCriterion("step_interval =", value, "stepInterval");
            return (Criteria) this;
        }

        public Criteria andStepIntervalNotEqualTo(Integer value) {
            addCriterion("step_interval <>", value, "stepInterval");
            return (Criteria) this;
        }

        public Criteria andStepIntervalGreaterThan(Integer value) {
            addCriterion("step_interval >", value, "stepInterval");
            return (Criteria) this;
        }

        public Criteria andStepIntervalGreaterThanOrEqualTo(Integer value) {
            addCriterion("step_interval >=", value, "stepInterval");
            return (Criteria) this;
        }

        public Criteria andStepIntervalLessThan(Integer value) {
            addCriterion("step_interval <", value, "stepInterval");
            return (Criteria) this;
        }

        public Criteria andStepIntervalLessThanOrEqualTo(Integer value) {
            addCriterion("step_interval <=", value, "stepInterval");
            return (Criteria) this;
        }

        public Criteria andStepIntervalIn(List<Integer> values) {
            addCriterion("step_interval in", values, "stepInterval");
            return (Criteria) this;
        }

        public Criteria andStepIntervalNotIn(List<Integer> values) {
            addCriterion("step_interval not in", values, "stepInterval");
            return (Criteria) this;
        }

        public Criteria andStepIntervalBetween(Integer value1, Integer value2) {
            addCriterion("step_interval between", value1, value2, "stepInterval");
            return (Criteria) this;
        }

        public Criteria andStepIntervalNotBetween(Integer value1, Integer value2) {
            addCriterion("step_interval not between", value1, value2, "stepInterval");
            return (Criteria) this;
        }

        public Criteria andStepUseStandardFrequencyIsNull() {
            addCriterion("step_use_standard_frequency is null");
            return (Criteria) this;
        }

        public Criteria andStepUseStandardFrequencyIsNotNull() {
            addCriterion("step_use_standard_frequency is not null");
            return (Criteria) this;
        }

        public Criteria andStepUseStandardFrequencyEqualTo(Byte value) {
            addCriterion("step_use_standard_frequency =", value, "stepUseStandardFrequency");
            return (Criteria) this;
        }

        public Criteria andStepUseStandardFrequencyNotEqualTo(Byte value) {
            addCriterion("step_use_standard_frequency <>", value, "stepUseStandardFrequency");
            return (Criteria) this;
        }

        public Criteria andStepUseStandardFrequencyGreaterThan(Byte value) {
            addCriterion("step_use_standard_frequency >", value, "stepUseStandardFrequency");
            return (Criteria) this;
        }

        public Criteria andStepUseStandardFrequencyGreaterThanOrEqualTo(Byte value) {
            addCriterion("step_use_standard_frequency >=", value, "stepUseStandardFrequency");
            return (Criteria) this;
        }

        public Criteria andStepUseStandardFrequencyLessThan(Byte value) {
            addCriterion("step_use_standard_frequency <", value, "stepUseStandardFrequency");
            return (Criteria) this;
        }

        public Criteria andStepUseStandardFrequencyLessThanOrEqualTo(Byte value) {
            addCriterion("step_use_standard_frequency <=", value, "stepUseStandardFrequency");
            return (Criteria) this;
        }

        public Criteria andStepUseStandardFrequencyIn(List<Byte> values) {
            addCriterion("step_use_standard_frequency in", values, "stepUseStandardFrequency");
            return (Criteria) this;
        }

        public Criteria andStepUseStandardFrequencyNotIn(List<Byte> values) {
            addCriterion("step_use_standard_frequency not in", values, "stepUseStandardFrequency");
            return (Criteria) this;
        }

        public Criteria andStepUseStandardFrequencyBetween(Byte value1, Byte value2) {
            addCriterion("step_use_standard_frequency between", value1, value2, "stepUseStandardFrequency");
            return (Criteria) this;
        }

        public Criteria andStepUseStandardFrequencyNotBetween(Byte value1, Byte value2) {
            addCriterion("step_use_standard_frequency not between", value1, value2, "stepUseStandardFrequency");
            return (Criteria) this;
        }

        public Criteria andStepUseStandardPeriodIsNull() {
            addCriterion("step_use_standard_period is null");
            return (Criteria) this;
        }

        public Criteria andStepUseStandardPeriodIsNotNull() {
            addCriterion("step_use_standard_period is not null");
            return (Criteria) this;
        }

        public Criteria andStepUseStandardPeriodEqualTo(Byte value) {
            addCriterion("step_use_standard_period =", value, "stepUseStandardPeriod");
            return (Criteria) this;
        }

        public Criteria andStepUseStandardPeriodNotEqualTo(Byte value) {
            addCriterion("step_use_standard_period <>", value, "stepUseStandardPeriod");
            return (Criteria) this;
        }

        public Criteria andStepUseStandardPeriodGreaterThan(Byte value) {
            addCriterion("step_use_standard_period >", value, "stepUseStandardPeriod");
            return (Criteria) this;
        }

        public Criteria andStepUseStandardPeriodGreaterThanOrEqualTo(Byte value) {
            addCriterion("step_use_standard_period >=", value, "stepUseStandardPeriod");
            return (Criteria) this;
        }

        public Criteria andStepUseStandardPeriodLessThan(Byte value) {
            addCriterion("step_use_standard_period <", value, "stepUseStandardPeriod");
            return (Criteria) this;
        }

        public Criteria andStepUseStandardPeriodLessThanOrEqualTo(Byte value) {
            addCriterion("step_use_standard_period <=", value, "stepUseStandardPeriod");
            return (Criteria) this;
        }

        public Criteria andStepUseStandardPeriodIn(List<Byte> values) {
            addCriterion("step_use_standard_period in", values, "stepUseStandardPeriod");
            return (Criteria) this;
        }

        public Criteria andStepUseStandardPeriodNotIn(List<Byte> values) {
            addCriterion("step_use_standard_period not in", values, "stepUseStandardPeriod");
            return (Criteria) this;
        }

        public Criteria andStepUseStandardPeriodBetween(Byte value1, Byte value2) {
            addCriterion("step_use_standard_period between", value1, value2, "stepUseStandardPeriod");
            return (Criteria) this;
        }

        public Criteria andStepUseStandardPeriodNotBetween(Byte value1, Byte value2) {
            addCriterion("step_use_standard_period not between", value1, value2, "stepUseStandardPeriod");
            return (Criteria) this;
        }

        public Criteria andStepUseStandardConditionIsNull() {
            addCriterion("step_use_standard_condition is null");
            return (Criteria) this;
        }

        public Criteria andStepUseStandardConditionIsNotNull() {
            addCriterion("step_use_standard_condition is not null");
            return (Criteria) this;
        }

        public Criteria andStepUseStandardConditionEqualTo(Byte value) {
            addCriterion("step_use_standard_condition =", value, "stepUseStandardCondition");
            return (Criteria) this;
        }

        public Criteria andStepUseStandardConditionNotEqualTo(Byte value) {
            addCriterion("step_use_standard_condition <>", value, "stepUseStandardCondition");
            return (Criteria) this;
        }

        public Criteria andStepUseStandardConditionGreaterThan(Byte value) {
            addCriterion("step_use_standard_condition >", value, "stepUseStandardCondition");
            return (Criteria) this;
        }

        public Criteria andStepUseStandardConditionGreaterThanOrEqualTo(Byte value) {
            addCriterion("step_use_standard_condition >=", value, "stepUseStandardCondition");
            return (Criteria) this;
        }

        public Criteria andStepUseStandardConditionLessThan(Byte value) {
            addCriterion("step_use_standard_condition <", value, "stepUseStandardCondition");
            return (Criteria) this;
        }

        public Criteria andStepUseStandardConditionLessThanOrEqualTo(Byte value) {
            addCriterion("step_use_standard_condition <=", value, "stepUseStandardCondition");
            return (Criteria) this;
        }

        public Criteria andStepUseStandardConditionIn(List<Byte> values) {
            addCriterion("step_use_standard_condition in", values, "stepUseStandardCondition");
            return (Criteria) this;
        }

        public Criteria andStepUseStandardConditionNotIn(List<Byte> values) {
            addCriterion("step_use_standard_condition not in", values, "stepUseStandardCondition");
            return (Criteria) this;
        }

        public Criteria andStepUseStandardConditionBetween(Byte value1, Byte value2) {
            addCriterion("step_use_standard_condition between", value1, value2, "stepUseStandardCondition");
            return (Criteria) this;
        }

        public Criteria andStepUseStandardConditionNotBetween(Byte value1, Byte value2) {
            addCriterion("step_use_standard_condition not between", value1, value2, "stepUseStandardCondition");
            return (Criteria) this;
        }

        public Criteria andUseTimeIsNull() {
            addCriterion("use_time is null");
            return (Criteria) this;
        }

        public Criteria andUseTimeIsNotNull() {
            addCriterion("use_time is not null");
            return (Criteria) this;
        }

        public Criteria andUseTimeEqualTo(Byte value) {
            addCriterion("use_time =", value, "useTime");
            return (Criteria) this;
        }

        public Criteria andUseTimeNotEqualTo(Byte value) {
            addCriterion("use_time <>", value, "useTime");
            return (Criteria) this;
        }

        public Criteria andUseTimeGreaterThan(Byte value) {
            addCriterion("use_time >", value, "useTime");
            return (Criteria) this;
        }

        public Criteria andUseTimeGreaterThanOrEqualTo(Byte value) {
            addCriterion("use_time >=", value, "useTime");
            return (Criteria) this;
        }

        public Criteria andUseTimeLessThan(Byte value) {
            addCriterion("use_time <", value, "useTime");
            return (Criteria) this;
        }

        public Criteria andUseTimeLessThanOrEqualTo(Byte value) {
            addCriterion("use_time <=", value, "useTime");
            return (Criteria) this;
        }

        public Criteria andUseTimeIn(List<Byte> values) {
            addCriterion("use_time in", values, "useTime");
            return (Criteria) this;
        }

        public Criteria andUseTimeNotIn(List<Byte> values) {
            addCriterion("use_time not in", values, "useTime");
            return (Criteria) this;
        }

        public Criteria andUseTimeBetween(Byte value1, Byte value2) {
            addCriterion("use_time between", value1, value2, "useTime");
            return (Criteria) this;
        }

        public Criteria andUseTimeNotBetween(Byte value1, Byte value2) {
            addCriterion("use_time not between", value1, value2, "useTime");
            return (Criteria) this;
        }

        public Criteria andProdIdIsNull() {
            addCriterion("prod_id is null");
            return (Criteria) this;
        }

        public Criteria andProdIdIsNotNull() {
            addCriterion("prod_id is not null");
            return (Criteria) this;
        }

        public Criteria andProdIdEqualTo(Long value) {
            addCriterion("prod_id =", value, "prodId");
            return (Criteria) this;
        }

        public Criteria andProdIdNotEqualTo(Long value) {
            addCriterion("prod_id <>", value, "prodId");
            return (Criteria) this;
        }

        public Criteria andProdIdGreaterThan(Long value) {
            addCriterion("prod_id >", value, "prodId");
            return (Criteria) this;
        }

        public Criteria andProdIdGreaterThanOrEqualTo(Long value) {
            addCriterion("prod_id >=", value, "prodId");
            return (Criteria) this;
        }

        public Criteria andProdIdLessThan(Long value) {
            addCriterion("prod_id <", value, "prodId");
            return (Criteria) this;
        }

        public Criteria andProdIdLessThanOrEqualTo(Long value) {
            addCriterion("prod_id <=", value, "prodId");
            return (Criteria) this;
        }

        public Criteria andProdIdIn(List<Long> values) {
            addCriterion("prod_id in", values, "prodId");
            return (Criteria) this;
        }

        public Criteria andProdIdNotIn(List<Long> values) {
            addCriterion("prod_id not in", values, "prodId");
            return (Criteria) this;
        }

        public Criteria andProdIdBetween(Long value1, Long value2) {
            addCriterion("prod_id between", value1, value2, "prodId");
            return (Criteria) this;
        }

        public Criteria andProdIdNotBetween(Long value1, Long value2) {
            addCriterion("prod_id not between", value1, value2, "prodId");
            return (Criteria) this;
        }

        public Criteria andProdUseRemindIsNull() {
            addCriterion("prod_use_remind is null");
            return (Criteria) this;
        }

        public Criteria andProdUseRemindIsNotNull() {
            addCriterion("prod_use_remind is not null");
            return (Criteria) this;
        }

        public Criteria andProdUseRemindEqualTo(String value) {
            addCriterion("prod_use_remind =", value, "prodUseRemind");
            return (Criteria) this;
        }

        public Criteria andProdUseRemindNotEqualTo(String value) {
            addCriterion("prod_use_remind <>", value, "prodUseRemind");
            return (Criteria) this;
        }

        public Criteria andProdUseRemindGreaterThan(String value) {
            addCriterion("prod_use_remind >", value, "prodUseRemind");
            return (Criteria) this;
        }

        public Criteria andProdUseRemindGreaterThanOrEqualTo(String value) {
            addCriterion("prod_use_remind >=", value, "prodUseRemind");
            return (Criteria) this;
        }

        public Criteria andProdUseRemindLessThan(String value) {
            addCriterion("prod_use_remind <", value, "prodUseRemind");
            return (Criteria) this;
        }

        public Criteria andProdUseRemindLessThanOrEqualTo(String value) {
            addCriterion("prod_use_remind <=", value, "prodUseRemind");
            return (Criteria) this;
        }

        public Criteria andProdUseRemindLike(String value) {
            addCriterion("prod_use_remind like", value, "prodUseRemind");
            return (Criteria) this;
        }

        public Criteria andProdUseRemindNotLike(String value) {
            addCriterion("prod_use_remind not like", value, "prodUseRemind");
            return (Criteria) this;
        }

        public Criteria andProdUseRemindIn(List<String> values) {
            addCriterion("prod_use_remind in", values, "prodUseRemind");
            return (Criteria) this;
        }

        public Criteria andProdUseRemindNotIn(List<String> values) {
            addCriterion("prod_use_remind not in", values, "prodUseRemind");
            return (Criteria) this;
        }

        public Criteria andProdUseRemindBetween(String value1, String value2) {
            addCriterion("prod_use_remind between", value1, value2, "prodUseRemind");
            return (Criteria) this;
        }

        public Criteria andProdUseRemindNotBetween(String value1, String value2) {
            addCriterion("prod_use_remind not between", value1, value2, "prodUseRemind");
            return (Criteria) this;
        }

        public Criteria andVideoNameIsNull() {
            addCriterion("video_name is null");
            return (Criteria) this;
        }

        public Criteria andVideoNameIsNotNull() {
            addCriterion("video_name is not null");
            return (Criteria) this;
        }

        public Criteria andVideoNameEqualTo(String value) {
            addCriterion("video_name =", value, "videoName");
            return (Criteria) this;
        }

        public Criteria andVideoNameNotEqualTo(String value) {
            addCriterion("video_name <>", value, "videoName");
            return (Criteria) this;
        }

        public Criteria andVideoNameGreaterThan(String value) {
            addCriterion("video_name >", value, "videoName");
            return (Criteria) this;
        }

        public Criteria andVideoNameGreaterThanOrEqualTo(String value) {
            addCriterion("video_name >=", value, "videoName");
            return (Criteria) this;
        }

        public Criteria andVideoNameLessThan(String value) {
            addCriterion("video_name <", value, "videoName");
            return (Criteria) this;
        }

        public Criteria andVideoNameLessThanOrEqualTo(String value) {
            addCriterion("video_name <=", value, "videoName");
            return (Criteria) this;
        }

        public Criteria andVideoNameLike(String value) {
            addCriterion("video_name like", value, "videoName");
            return (Criteria) this;
        }

        public Criteria andVideoNameNotLike(String value) {
            addCriterion("video_name not like", value, "videoName");
            return (Criteria) this;
        }

        public Criteria andVideoNameIn(List<String> values) {
            addCriterion("video_name in", values, "videoName");
            return (Criteria) this;
        }

        public Criteria andVideoNameNotIn(List<String> values) {
            addCriterion("video_name not in", values, "videoName");
            return (Criteria) this;
        }

        public Criteria andVideoNameBetween(String value1, String value2) {
            addCriterion("video_name between", value1, value2, "videoName");
            return (Criteria) this;
        }

        public Criteria andVideoNameNotBetween(String value1, String value2) {
            addCriterion("video_name not between", value1, value2, "videoName");
            return (Criteria) this;
        }

        public Criteria andVideoShortNameIsNull() {
            addCriterion("video_short_name is null");
            return (Criteria) this;
        }

        public Criteria andVideoShortNameIsNotNull() {
            addCriterion("video_short_name is not null");
            return (Criteria) this;
        }

        public Criteria andVideoShortNameEqualTo(String value) {
            addCriterion("video_short_name =", value, "videoShortName");
            return (Criteria) this;
        }

        public Criteria andVideoShortNameNotEqualTo(String value) {
            addCriterion("video_short_name <>", value, "videoShortName");
            return (Criteria) this;
        }

        public Criteria andVideoShortNameGreaterThan(String value) {
            addCriterion("video_short_name >", value, "videoShortName");
            return (Criteria) this;
        }

        public Criteria andVideoShortNameGreaterThanOrEqualTo(String value) {
            addCriterion("video_short_name >=", value, "videoShortName");
            return (Criteria) this;
        }

        public Criteria andVideoShortNameLessThan(String value) {
            addCriterion("video_short_name <", value, "videoShortName");
            return (Criteria) this;
        }

        public Criteria andVideoShortNameLessThanOrEqualTo(String value) {
            addCriterion("video_short_name <=", value, "videoShortName");
            return (Criteria) this;
        }

        public Criteria andVideoShortNameLike(String value) {
            addCriterion("video_short_name like", value, "videoShortName");
            return (Criteria) this;
        }

        public Criteria andVideoShortNameNotLike(String value) {
            addCriterion("video_short_name not like", value, "videoShortName");
            return (Criteria) this;
        }

        public Criteria andVideoShortNameIn(List<String> values) {
            addCriterion("video_short_name in", values, "videoShortName");
            return (Criteria) this;
        }

        public Criteria andVideoShortNameNotIn(List<String> values) {
            addCriterion("video_short_name not in", values, "videoShortName");
            return (Criteria) this;
        }

        public Criteria andVideoShortNameBetween(String value1, String value2) {
            addCriterion("video_short_name between", value1, value2, "videoShortName");
            return (Criteria) this;
        }

        public Criteria andVideoShortNameNotBetween(String value1, String value2) {
            addCriterion("video_short_name not between", value1, value2, "videoShortName");
            return (Criteria) this;
        }

        public Criteria andVideoUrlIsNull() {
            addCriterion("video_url is null");
            return (Criteria) this;
        }

        public Criteria andVideoUrlIsNotNull() {
            addCriterion("video_url is not null");
            return (Criteria) this;
        }

        public Criteria andVideoUrlEqualTo(String value) {
            addCriterion("video_url =", value, "videoUrl");
            return (Criteria) this;
        }

        public Criteria andVideoUrlNotEqualTo(String value) {
            addCriterion("video_url <>", value, "videoUrl");
            return (Criteria) this;
        }

        public Criteria andVideoUrlGreaterThan(String value) {
            addCriterion("video_url >", value, "videoUrl");
            return (Criteria) this;
        }

        public Criteria andVideoUrlGreaterThanOrEqualTo(String value) {
            addCriterion("video_url >=", value, "videoUrl");
            return (Criteria) this;
        }

        public Criteria andVideoUrlLessThan(String value) {
            addCriterion("video_url <", value, "videoUrl");
            return (Criteria) this;
        }

        public Criteria andVideoUrlLessThanOrEqualTo(String value) {
            addCriterion("video_url <=", value, "videoUrl");
            return (Criteria) this;
        }

        public Criteria andVideoUrlLike(String value) {
            addCriterion("video_url like", value, "videoUrl");
            return (Criteria) this;
        }

        public Criteria andVideoUrlNotLike(String value) {
            addCriterion("video_url not like", value, "videoUrl");
            return (Criteria) this;
        }

        public Criteria andVideoUrlIn(List<String> values) {
            addCriterion("video_url in", values, "videoUrl");
            return (Criteria) this;
        }

        public Criteria andVideoUrlNotIn(List<String> values) {
            addCriterion("video_url not in", values, "videoUrl");
            return (Criteria) this;
        }

        public Criteria andVideoUrlBetween(String value1, String value2) {
            addCriterion("video_url between", value1, value2, "videoUrl");
            return (Criteria) this;
        }

        public Criteria andVideoUrlNotBetween(String value1, String value2) {
            addCriterion("video_url not between", value1, value2, "videoUrl");
            return (Criteria) this;
        }

        public Criteria andVideoTimeIsNull() {
            addCriterion("video_time is null");
            return (Criteria) this;
        }

        public Criteria andVideoTimeIsNotNull() {
            addCriterion("video_time is not null");
            return (Criteria) this;
        }

        public Criteria andVideoTimeEqualTo(Integer value) {
            addCriterion("video_time =", value, "videoTime");
            return (Criteria) this;
        }

        public Criteria andVideoTimeNotEqualTo(Integer value) {
            addCriterion("video_time <>", value, "videoTime");
            return (Criteria) this;
        }

        public Criteria andVideoTimeGreaterThan(Integer value) {
            addCriterion("video_time >", value, "videoTime");
            return (Criteria) this;
        }

        public Criteria andVideoTimeGreaterThanOrEqualTo(Integer value) {
            addCriterion("video_time >=", value, "videoTime");
            return (Criteria) this;
        }

        public Criteria andVideoTimeLessThan(Integer value) {
            addCriterion("video_time <", value, "videoTime");
            return (Criteria) this;
        }

        public Criteria andVideoTimeLessThanOrEqualTo(Integer value) {
            addCriterion("video_time <=", value, "videoTime");
            return (Criteria) this;
        }

        public Criteria andVideoTimeIn(List<Integer> values) {
            addCriterion("video_time in", values, "videoTime");
            return (Criteria) this;
        }

        public Criteria andVideoTimeNotIn(List<Integer> values) {
            addCriterion("video_time not in", values, "videoTime");
            return (Criteria) this;
        }

        public Criteria andVideoTimeBetween(Integer value1, Integer value2) {
            addCriterion("video_time between", value1, value2, "videoTime");
            return (Criteria) this;
        }

        public Criteria andVideoTimeNotBetween(Integer value1, Integer value2) {
            addCriterion("video_time not between", value1, value2, "videoTime");
            return (Criteria) this;
        }

        public Criteria andVideoUseRemindIsNull() {
            addCriterion("video_use_remind is null");
            return (Criteria) this;
        }

        public Criteria andVideoUseRemindIsNotNull() {
            addCriterion("video_use_remind is not null");
            return (Criteria) this;
        }

        public Criteria andVideoUseRemindEqualTo(String value) {
            addCriterion("video_use_remind =", value, "videoUseRemind");
            return (Criteria) this;
        }

        public Criteria andVideoUseRemindNotEqualTo(String value) {
            addCriterion("video_use_remind <>", value, "videoUseRemind");
            return (Criteria) this;
        }

        public Criteria andVideoUseRemindGreaterThan(String value) {
            addCriterion("video_use_remind >", value, "videoUseRemind");
            return (Criteria) this;
        }

        public Criteria andVideoUseRemindGreaterThanOrEqualTo(String value) {
            addCriterion("video_use_remind >=", value, "videoUseRemind");
            return (Criteria) this;
        }

        public Criteria andVideoUseRemindLessThan(String value) {
            addCriterion("video_use_remind <", value, "videoUseRemind");
            return (Criteria) this;
        }

        public Criteria andVideoUseRemindLessThanOrEqualTo(String value) {
            addCriterion("video_use_remind <=", value, "videoUseRemind");
            return (Criteria) this;
        }

        public Criteria andVideoUseRemindLike(String value) {
            addCriterion("video_use_remind like", value, "videoUseRemind");
            return (Criteria) this;
        }

        public Criteria andVideoUseRemindNotLike(String value) {
            addCriterion("video_use_remind not like", value, "videoUseRemind");
            return (Criteria) this;
        }

        public Criteria andVideoUseRemindIn(List<String> values) {
            addCriterion("video_use_remind in", values, "videoUseRemind");
            return (Criteria) this;
        }

        public Criteria andVideoUseRemindNotIn(List<String> values) {
            addCriterion("video_use_remind not in", values, "videoUseRemind");
            return (Criteria) this;
        }

        public Criteria andVideoUseRemindBetween(String value1, String value2) {
            addCriterion("video_use_remind between", value1, value2, "videoUseRemind");
            return (Criteria) this;
        }

        public Criteria andVideoUseRemindNotBetween(String value1, String value2) {
            addCriterion("video_use_remind not between", value1, value2, "videoUseRemind");
            return (Criteria) this;
        }

        public Criteria andVersionIsNull() {
            addCriterion("version is null");
            return (Criteria) this;
        }

        public Criteria andVersionIsNotNull() {
            addCriterion("version is not null");
            return (Criteria) this;
        }

        public Criteria andVersionEqualTo(Long value) {
            addCriterion("version =", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotEqualTo(Long value) {
            addCriterion("version <>", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionGreaterThan(Long value) {
            addCriterion("version >", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionGreaterThanOrEqualTo(Long value) {
            addCriterion("version >=", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLessThan(Long value) {
            addCriterion("version <", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLessThanOrEqualTo(Long value) {
            addCriterion("version <=", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionIn(List<Long> values) {
            addCriterion("version in", values, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotIn(List<Long> values) {
            addCriterion("version not in", values, "version");
            return (Criteria) this;
        }

        public Criteria andVersionBetween(Long value1, Long value2) {
            addCriterion("version between", value1, value2, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotBetween(Long value1, Long value2) {
            addCriterion("version not between", value1, value2, "version");
            return (Criteria) this;
        }

        public Criteria andDateCreatedIsNull() {
            addCriterion("date_created is null");
            return (Criteria) this;
        }

        public Criteria andDateCreatedIsNotNull() {
            addCriterion("date_created is not null");
            return (Criteria) this;
        }

        public Criteria andDateCreatedEqualTo(Date value) {
            addCriterion("date_created =", value, "dateCreated");
            return (Criteria) this;
        }

        public Criteria andDateCreatedNotEqualTo(Date value) {
            addCriterion("date_created <>", value, "dateCreated");
            return (Criteria) this;
        }

        public Criteria andDateCreatedGreaterThan(Date value) {
            addCriterion("date_created >", value, "dateCreated");
            return (Criteria) this;
        }

        public Criteria andDateCreatedGreaterThanOrEqualTo(Date value) {
            addCriterion("date_created >=", value, "dateCreated");
            return (Criteria) this;
        }

        public Criteria andDateCreatedLessThan(Date value) {
            addCriterion("date_created <", value, "dateCreated");
            return (Criteria) this;
        }

        public Criteria andDateCreatedLessThanOrEqualTo(Date value) {
            addCriterion("date_created <=", value, "dateCreated");
            return (Criteria) this;
        }

        public Criteria andDateCreatedIn(List<Date> values) {
            addCriterion("date_created in", values, "dateCreated");
            return (Criteria) this;
        }

        public Criteria andDateCreatedNotIn(List<Date> values) {
            addCriterion("date_created not in", values, "dateCreated");
            return (Criteria) this;
        }

        public Criteria andDateCreatedBetween(Date value1, Date value2) {
            addCriterion("date_created between", value1, value2, "dateCreated");
            return (Criteria) this;
        }

        public Criteria andDateCreatedNotBetween(Date value1, Date value2) {
            addCriterion("date_created not between", value1, value2, "dateCreated");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedIsNull() {
            addCriterion("last_updated is null");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedIsNotNull() {
            addCriterion("last_updated is not null");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedEqualTo(Date value) {
            addCriterion("last_updated =", value, "lastUpdated");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedNotEqualTo(Date value) {
            addCriterion("last_updated <>", value, "lastUpdated");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedGreaterThan(Date value) {
            addCriterion("last_updated >", value, "lastUpdated");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedGreaterThanOrEqualTo(Date value) {
            addCriterion("last_updated >=", value, "lastUpdated");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedLessThan(Date value) {
            addCriterion("last_updated <", value, "lastUpdated");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedLessThanOrEqualTo(Date value) {
            addCriterion("last_updated <=", value, "lastUpdated");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedIn(List<Date> values) {
            addCriterion("last_updated in", values, "lastUpdated");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedNotIn(List<Date> values) {
            addCriterion("last_updated not in", values, "lastUpdated");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedBetween(Date value1, Date value2) {
            addCriterion("last_updated between", value1, value2, "lastUpdated");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedNotBetween(Date value1, Date value2) {
            addCriterion("last_updated not between", value1, value2, "lastUpdated");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table miku_mine_course_step
     *
     * @mbggenerated do_not_delete_during_merge Sat May 21 16:59:55 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table miku_mine_course_step
     *
     * @mbggenerated Sat May 21 16:59:55 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}