package com.welink.commons.domain;

import java.util.Date;

public class MikuMineDetectReportDO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miku_mine_detect_report.id
     *
     * @mbggenerated Fri May 13 11:11:41 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miku_mine_detect_report.version
     *
     * @mbggenerated Fri May 13 11:11:41 CST 2016
     */
    private Long version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miku_mine_detect_report.date_created
     *
     * @mbggenerated Fri May 13 11:11:41 CST 2016
     */
    private Date dateCreated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miku_mine_detect_report.instrument_measure_date_include
     *
     * @mbggenerated Fri May 13 11:11:41 CST 2016
     */
    private String instrumentMeasureDateInclude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miku_mine_detect_report.instrument_measure_etime
     *
     * @mbggenerated Fri May 13 11:11:41 CST 2016
     */
    private Date instrumentMeasureEtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miku_mine_detect_report.instrument_measure_stime
     *
     * @mbggenerated Fri May 13 11:11:41 CST 2016
     */
    private Date instrumentMeasureStime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miku_mine_detect_report.instrument_type
     *
     * @mbggenerated Fri May 13 11:11:41 CST 2016
     */
    private Byte instrumentType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miku_mine_detect_report.last_updated
     *
     * @mbggenerated Fri May 13 11:11:41 CST 2016
     */
    private Date lastUpdated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miku_mine_detect_report.money
     *
     * @mbggenerated Fri May 13 11:11:41 CST 2016
     */
    private String money;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miku_mine_detect_report.option_id
     *
     * @mbggenerated Fri May 13 11:11:41 CST 2016
     */
    private Long optionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miku_mine_detect_report.option_show_style
     *
     * @mbggenerated Fri May 13 11:11:41 CST 2016
     */
    private String optionShowStyle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miku_mine_detect_report.option_value
     *
     * @mbggenerated Fri May 13 11:11:41 CST 2016
     */
    private String optionValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miku_mine_detect_report.pic_urls
     *
     * @mbggenerated Fri May 13 11:11:41 CST 2016
     */
    private String picUrls;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miku_mine_detect_report.question_id
     *
     * @mbggenerated Fri May 13 11:11:41 CST 2016
     */
    private Long questionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miku_mine_detect_report.question_name
     *
     * @mbggenerated Fri May 13 11:11:41 CST 2016
     */
    private String questionName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miku_mine_detect_report.question_order_inreport
     *
     * @mbggenerated Fri May 13 11:11:41 CST 2016
     */
    private String questionOrderInreport;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miku_mine_detect_report.question_postion_inreport
     *
     * @mbggenerated Fri May 13 11:11:41 CST 2016
     */
    private String questionPostionInreport;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miku_mine_detect_report.question_type
     *
     * @mbggenerated Fri May 13 11:11:41 CST 2016
     */
    private String questionType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miku_mine_detect_report.questionnaire_id
     *
     * @mbggenerated Fri May 13 11:11:41 CST 2016
     */
    private Long questionnaireId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miku_mine_detect_report.service_id
     *
     * @mbggenerated Fri May 13 11:11:41 CST 2016
     */
    private Long serviceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miku_mine_detect_report.user_id
     *
     * @mbggenerated Fri May 13 11:11:41 CST 2016
     */
    private Long userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miku_mine_detect_report.id
     *
     * @return the value of miku_mine_detect_report.id
     *
     * @mbggenerated Fri May 13 11:11:41 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miku_mine_detect_report.id
     *
     * @param id the value for miku_mine_detect_report.id
     *
     * @mbggenerated Fri May 13 11:11:41 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miku_mine_detect_report.version
     *
     * @return the value of miku_mine_detect_report.version
     *
     * @mbggenerated Fri May 13 11:11:41 CST 2016
     */
    public Long getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miku_mine_detect_report.version
     *
     * @param version the value for miku_mine_detect_report.version
     *
     * @mbggenerated Fri May 13 11:11:41 CST 2016
     */
    public void setVersion(Long version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miku_mine_detect_report.date_created
     *
     * @return the value of miku_mine_detect_report.date_created
     *
     * @mbggenerated Fri May 13 11:11:41 CST 2016
     */
    public Date getDateCreated() {
        return dateCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miku_mine_detect_report.date_created
     *
     * @param dateCreated the value for miku_mine_detect_report.date_created
     *
     * @mbggenerated Fri May 13 11:11:41 CST 2016
     */
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miku_mine_detect_report.instrument_measure_date_include
     *
     * @return the value of miku_mine_detect_report.instrument_measure_date_include
     *
     * @mbggenerated Fri May 13 11:11:41 CST 2016
     */
    public String getInstrumentMeasureDateInclude() {
        return instrumentMeasureDateInclude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miku_mine_detect_report.instrument_measure_date_include
     *
     * @param instrumentMeasureDateInclude the value for miku_mine_detect_report.instrument_measure_date_include
     *
     * @mbggenerated Fri May 13 11:11:41 CST 2016
     */
    public void setInstrumentMeasureDateInclude(String instrumentMeasureDateInclude) {
        this.instrumentMeasureDateInclude = instrumentMeasureDateInclude == null ? null : instrumentMeasureDateInclude.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miku_mine_detect_report.instrument_measure_etime
     *
     * @return the value of miku_mine_detect_report.instrument_measure_etime
     *
     * @mbggenerated Fri May 13 11:11:41 CST 2016
     */
    public Date getInstrumentMeasureEtime() {
        return instrumentMeasureEtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miku_mine_detect_report.instrument_measure_etime
     *
     * @param instrumentMeasureEtime the value for miku_mine_detect_report.instrument_measure_etime
     *
     * @mbggenerated Fri May 13 11:11:41 CST 2016
     */
    public void setInstrumentMeasureEtime(Date instrumentMeasureEtime) {
        this.instrumentMeasureEtime = instrumentMeasureEtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miku_mine_detect_report.instrument_measure_stime
     *
     * @return the value of miku_mine_detect_report.instrument_measure_stime
     *
     * @mbggenerated Fri May 13 11:11:41 CST 2016
     */
    public Date getInstrumentMeasureStime() {
        return instrumentMeasureStime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miku_mine_detect_report.instrument_measure_stime
     *
     * @param instrumentMeasureStime the value for miku_mine_detect_report.instrument_measure_stime
     *
     * @mbggenerated Fri May 13 11:11:41 CST 2016
     */
    public void setInstrumentMeasureStime(Date instrumentMeasureStime) {
        this.instrumentMeasureStime = instrumentMeasureStime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miku_mine_detect_report.instrument_type
     *
     * @return the value of miku_mine_detect_report.instrument_type
     *
     * @mbggenerated Fri May 13 11:11:41 CST 2016
     */
    public Byte getInstrumentType() {
        return instrumentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miku_mine_detect_report.instrument_type
     *
     * @param instrumentType the value for miku_mine_detect_report.instrument_type
     *
     * @mbggenerated Fri May 13 11:11:41 CST 2016
     */
    public void setInstrumentType(Byte instrumentType) {
        this.instrumentType = instrumentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miku_mine_detect_report.last_updated
     *
     * @return the value of miku_mine_detect_report.last_updated
     *
     * @mbggenerated Fri May 13 11:11:41 CST 2016
     */
    public Date getLastUpdated() {
        return lastUpdated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miku_mine_detect_report.last_updated
     *
     * @param lastUpdated the value for miku_mine_detect_report.last_updated
     *
     * @mbggenerated Fri May 13 11:11:41 CST 2016
     */
    public void setLastUpdated(Date lastUpdated) {
        this.lastUpdated = lastUpdated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miku_mine_detect_report.money
     *
     * @return the value of miku_mine_detect_report.money
     *
     * @mbggenerated Fri May 13 11:11:41 CST 2016
     */
    public String getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miku_mine_detect_report.money
     *
     * @param money the value for miku_mine_detect_report.money
     *
     * @mbggenerated Fri May 13 11:11:41 CST 2016
     */
    public void setMoney(String money) {
        this.money = money == null ? null : money.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miku_mine_detect_report.option_id
     *
     * @return the value of miku_mine_detect_report.option_id
     *
     * @mbggenerated Fri May 13 11:11:41 CST 2016
     */
    public Long getOptionId() {
        return optionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miku_mine_detect_report.option_id
     *
     * @param optionId the value for miku_mine_detect_report.option_id
     *
     * @mbggenerated Fri May 13 11:11:41 CST 2016
     */
    public void setOptionId(Long optionId) {
        this.optionId = optionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miku_mine_detect_report.option_show_style
     *
     * @return the value of miku_mine_detect_report.option_show_style
     *
     * @mbggenerated Fri May 13 11:11:41 CST 2016
     */
    public String getOptionShowStyle() {
        return optionShowStyle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miku_mine_detect_report.option_show_style
     *
     * @param optionShowStyle the value for miku_mine_detect_report.option_show_style
     *
     * @mbggenerated Fri May 13 11:11:41 CST 2016
     */
    public void setOptionShowStyle(String optionShowStyle) {
        this.optionShowStyle = optionShowStyle == null ? null : optionShowStyle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miku_mine_detect_report.option_value
     *
     * @return the value of miku_mine_detect_report.option_value
     *
     * @mbggenerated Fri May 13 11:11:41 CST 2016
     */
    public String getOptionValue() {
        return optionValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miku_mine_detect_report.option_value
     *
     * @param optionValue the value for miku_mine_detect_report.option_value
     *
     * @mbggenerated Fri May 13 11:11:41 CST 2016
     */
    public void setOptionValue(String optionValue) {
        this.optionValue = optionValue == null ? null : optionValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miku_mine_detect_report.pic_urls
     *
     * @return the value of miku_mine_detect_report.pic_urls
     *
     * @mbggenerated Fri May 13 11:11:41 CST 2016
     */
    public String getPicUrls() {
        return picUrls;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miku_mine_detect_report.pic_urls
     *
     * @param picUrls the value for miku_mine_detect_report.pic_urls
     *
     * @mbggenerated Fri May 13 11:11:41 CST 2016
     */
    public void setPicUrls(String picUrls) {
        this.picUrls = picUrls == null ? null : picUrls.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miku_mine_detect_report.question_id
     *
     * @return the value of miku_mine_detect_report.question_id
     *
     * @mbggenerated Fri May 13 11:11:41 CST 2016
     */
    public Long getQuestionId() {
        return questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miku_mine_detect_report.question_id
     *
     * @param questionId the value for miku_mine_detect_report.question_id
     *
     * @mbggenerated Fri May 13 11:11:41 CST 2016
     */
    public void setQuestionId(Long questionId) {
        this.questionId = questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miku_mine_detect_report.question_name
     *
     * @return the value of miku_mine_detect_report.question_name
     *
     * @mbggenerated Fri May 13 11:11:41 CST 2016
     */
    public String getQuestionName() {
        return questionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miku_mine_detect_report.question_name
     *
     * @param questionName the value for miku_mine_detect_report.question_name
     *
     * @mbggenerated Fri May 13 11:11:41 CST 2016
     */
    public void setQuestionName(String questionName) {
        this.questionName = questionName == null ? null : questionName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miku_mine_detect_report.question_order_inreport
     *
     * @return the value of miku_mine_detect_report.question_order_inreport
     *
     * @mbggenerated Fri May 13 11:11:41 CST 2016
     */
    public String getQuestionOrderInreport() {
        return questionOrderInreport;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miku_mine_detect_report.question_order_inreport
     *
     * @param questionOrderInreport the value for miku_mine_detect_report.question_order_inreport
     *
     * @mbggenerated Fri May 13 11:11:41 CST 2016
     */
    public void setQuestionOrderInreport(String questionOrderInreport) {
        this.questionOrderInreport = questionOrderInreport == null ? null : questionOrderInreport.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miku_mine_detect_report.question_postion_inreport
     *
     * @return the value of miku_mine_detect_report.question_postion_inreport
     *
     * @mbggenerated Fri May 13 11:11:41 CST 2016
     */
    public String getQuestionPostionInreport() {
        return questionPostionInreport;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miku_mine_detect_report.question_postion_inreport
     *
     * @param questionPostionInreport the value for miku_mine_detect_report.question_postion_inreport
     *
     * @mbggenerated Fri May 13 11:11:41 CST 2016
     */
    public void setQuestionPostionInreport(String questionPostionInreport) {
        this.questionPostionInreport = questionPostionInreport == null ? null : questionPostionInreport.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miku_mine_detect_report.question_type
     *
     * @return the value of miku_mine_detect_report.question_type
     *
     * @mbggenerated Fri May 13 11:11:41 CST 2016
     */
    public String getQuestionType() {
        return questionType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miku_mine_detect_report.question_type
     *
     * @param questionType the value for miku_mine_detect_report.question_type
     *
     * @mbggenerated Fri May 13 11:11:41 CST 2016
     */
    public void setQuestionType(String questionType) {
        this.questionType = questionType == null ? null : questionType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miku_mine_detect_report.questionnaire_id
     *
     * @return the value of miku_mine_detect_report.questionnaire_id
     *
     * @mbggenerated Fri May 13 11:11:41 CST 2016
     */
    public Long getQuestionnaireId() {
        return questionnaireId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miku_mine_detect_report.questionnaire_id
     *
     * @param questionnaireId the value for miku_mine_detect_report.questionnaire_id
     *
     * @mbggenerated Fri May 13 11:11:41 CST 2016
     */
    public void setQuestionnaireId(Long questionnaireId) {
        this.questionnaireId = questionnaireId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miku_mine_detect_report.service_id
     *
     * @return the value of miku_mine_detect_report.service_id
     *
     * @mbggenerated Fri May 13 11:11:41 CST 2016
     */
    public Long getServiceId() {
        return serviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miku_mine_detect_report.service_id
     *
     * @param serviceId the value for miku_mine_detect_report.service_id
     *
     * @mbggenerated Fri May 13 11:11:41 CST 2016
     */
    public void setServiceId(Long serviceId) {
        this.serviceId = serviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miku_mine_detect_report.user_id
     *
     * @return the value of miku_mine_detect_report.user_id
     *
     * @mbggenerated Fri May 13 11:11:41 CST 2016
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miku_mine_detect_report.user_id
     *
     * @param userId the value for miku_mine_detect_report.user_id
     *
     * @mbggenerated Fri May 13 11:11:41 CST 2016
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }
}