package com.welink.commons.domain;

import java.util.Date;

public class ServiceConfigDO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column service_config.id
     *
     * @mbggenerated Thu Nov 27 18:10:21 CST 2014
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column service_config.community_id
     *
     * @mbggenerated Thu Nov 27 18:10:21 CST 2014
     */
    private Long communityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column service_config.service_id
     *
     * @mbggenerated Thu Nov 27 18:10:21 CST 2014
     */
    private Byte serviceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column service_config.service_name
     *
     * @mbggenerated Thu Nov 27 18:10:21 CST 2014
     */
    private String serviceName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column service_config.community_pic
     *
     * @mbggenerated Thu Nov 27 18:10:21 CST 2014
     */
    private String communityPic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column service_config.date_created
     *
     * @mbggenerated Thu Nov 27 18:10:21 CST 2014
     */
    private Date dateCreated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column service_config.last_update
     *
     * @mbggenerated Thu Nov 27 18:10:21 CST 2014
     */
    private Date lastUpdate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column service_config.id
     *
     * @return the value of service_config.id
     * @mbggenerated Thu Nov 27 18:10:21 CST 2014
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column service_config.id
     *
     * @param id the value for service_config.id
     * @mbggenerated Thu Nov 27 18:10:21 CST 2014
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column service_config.community_id
     *
     * @return the value of service_config.community_id
     * @mbggenerated Thu Nov 27 18:10:21 CST 2014
     */
    public Long getCommunityId() {
        return communityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column service_config.community_id
     *
     * @param communityId the value for service_config.community_id
     * @mbggenerated Thu Nov 27 18:10:21 CST 2014
     */
    public void setCommunityId(Long communityId) {
        this.communityId = communityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column service_config.service_id
     *
     * @return the value of service_config.service_id
     * @mbggenerated Thu Nov 27 18:10:21 CST 2014
     */
    public Byte getServiceId() {
        return serviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column service_config.service_id
     *
     * @param serviceId the value for service_config.service_id
     * @mbggenerated Thu Nov 27 18:10:21 CST 2014
     */
    public void setServiceId(Byte serviceId) {
        this.serviceId = serviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column service_config.service_name
     *
     * @return the value of service_config.service_name
     * @mbggenerated Thu Nov 27 18:10:21 CST 2014
     */
    public String getServiceName() {
        return serviceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column service_config.service_name
     *
     * @param serviceName the value for service_config.service_name
     * @mbggenerated Thu Nov 27 18:10:21 CST 2014
     */
    public void setServiceName(String serviceName) {
        this.serviceName = serviceName == null ? null : serviceName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column service_config.community_pic
     *
     * @return the value of service_config.community_pic
     * @mbggenerated Thu Nov 27 18:10:21 CST 2014
     */
    public String getCommunityPic() {
        return communityPic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column service_config.community_pic
     *
     * @param communityPic the value for service_config.community_pic
     * @mbggenerated Thu Nov 27 18:10:21 CST 2014
     */
    public void setCommunityPic(String communityPic) {
        this.communityPic = communityPic == null ? null : communityPic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column service_config.date_created
     *
     * @return the value of service_config.date_created
     * @mbggenerated Thu Nov 27 18:10:21 CST 2014
     */
    public Date getDateCreated() {
        return dateCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column service_config.date_created
     *
     * @param dateCreated the value for service_config.date_created
     * @mbggenerated Thu Nov 27 18:10:21 CST 2014
     */
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column service_config.last_update
     *
     * @return the value of service_config.last_update
     * @mbggenerated Thu Nov 27 18:10:21 CST 2014
     */
    public Date getLastUpdate() {
        return lastUpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column service_config.last_update
     *
     * @param lastUpdate the value for service_config.last_update
     * @mbggenerated Thu Nov 27 18:10:21 CST 2014
     */
    public void setLastUpdate(Date lastUpdate) {
        this.lastUpdate = lastUpdate;
    }
}