package com.welink.commons.domain;

import java.math.BigInteger;
import java.util.Date;

public class TagsDO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tags.id
     *
     * @mbggenerated Mon Mar 30 19:10:38 CST 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tags.version
     *
     * @mbggenerated Mon Mar 30 19:10:38 CST 2015
     */
    private Long version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tags.tag_id
     *
     * @mbggenerated Mon Mar 30 19:10:38 CST 2015
     */
    private String tagId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tags.name
     *
     * @mbggenerated Mon Mar 30 19:10:38 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tags.kv
     *
     * @mbggenerated Mon Mar 30 19:10:38 CST 2015
     */
    private String kv;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tags.bit
     *
     * @mbggenerated Mon Mar 30 19:10:38 CST 2015
     */
    private BigInteger bit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tags.pic
     *
     * @mbggenerated Mon Mar 30 19:10:38 CST 2015
     */
    private String pic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tags.status
     *
     * @mbggenerated Mon Mar 30 19:10:38 CST 2015
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tags.type
     *
     * @mbggenerated Mon Mar 30 19:10:38 CST 2015
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tags.weight
     *
     * @mbggenerated Mon Mar 30 19:10:38 CST 2015
     */
    private Integer weight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tags.date_created
     *
     * @mbggenerated Mon Mar 30 19:10:38 CST 2015
     */
    private Date dateCreated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tags.last_updated
     *
     * @mbggenerated Mon Mar 30 19:10:38 CST 2015
     */
    private Date lastUpdated;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tags.id
     *
     * @return the value of tags.id
     * @mbggenerated Mon Mar 30 19:10:38 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tags.id
     *
     * @param id the value for tags.id
     * @mbggenerated Mon Mar 30 19:10:38 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tags.version
     *
     * @return the value of tags.version
     * @mbggenerated Mon Mar 30 19:10:38 CST 2015
     */
    public Long getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tags.version
     *
     * @param version the value for tags.version
     * @mbggenerated Mon Mar 30 19:10:38 CST 2015
     */
    public void setVersion(Long version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tags.tag_id
     *
     * @return the value of tags.tag_id
     * @mbggenerated Mon Mar 30 19:10:38 CST 2015
     */
    public String getTagId() {
        return tagId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tags.tag_id
     *
     * @param tagId the value for tags.tag_id
     * @mbggenerated Mon Mar 30 19:10:38 CST 2015
     */
    public void setTagId(String tagId) {
        this.tagId = tagId == null ? null : tagId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tags.name
     *
     * @return the value of tags.name
     * @mbggenerated Mon Mar 30 19:10:38 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tags.name
     *
     * @param name the value for tags.name
     * @mbggenerated Mon Mar 30 19:10:38 CST 2015
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tags.kv
     *
     * @return the value of tags.kv
     * @mbggenerated Mon Mar 30 19:10:38 CST 2015
     */
    public String getKv() {
        return kv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tags.kv
     *
     * @param kv the value for tags.kv
     * @mbggenerated Mon Mar 30 19:10:38 CST 2015
     */
    public void setKv(String kv) {
        this.kv = kv == null ? null : kv.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tags.bit
     *
     * @return the value of tags.bit
     * @mbggenerated Mon Mar 30 19:10:38 CST 2015
     */
    public BigInteger getBit() {
        return bit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tags.bit
     *
     * @param bit the value for tags.bit
     * @mbggenerated Mon Mar 30 19:10:38 CST 2015
     */
    public void setBit(BigInteger bit) {
        this.bit = bit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tags.pic
     *
     * @return the value of tags.pic
     * @mbggenerated Mon Mar 30 19:10:38 CST 2015
     */
    public String getPic() {
        return pic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tags.pic
     *
     * @param pic the value for tags.pic
     * @mbggenerated Mon Mar 30 19:10:38 CST 2015
     */
    public void setPic(String pic) {
        this.pic = pic == null ? null : pic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tags.status
     *
     * @return the value of tags.status
     * @mbggenerated Mon Mar 30 19:10:38 CST 2015
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tags.status
     *
     * @param status the value for tags.status
     * @mbggenerated Mon Mar 30 19:10:38 CST 2015
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tags.type
     *
     * @return the value of tags.type
     * @mbggenerated Mon Mar 30 19:10:38 CST 2015
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tags.type
     *
     * @param type the value for tags.type
     * @mbggenerated Mon Mar 30 19:10:38 CST 2015
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tags.weight
     *
     * @return the value of tags.weight
     * @mbggenerated Mon Mar 30 19:10:38 CST 2015
     */
    public Integer getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tags.weight
     *
     * @param weight the value for tags.weight
     * @mbggenerated Mon Mar 30 19:10:38 CST 2015
     */
    public void setWeight(Integer weight) {
        this.weight = weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tags.date_created
     *
     * @return the value of tags.date_created
     * @mbggenerated Mon Mar 30 19:10:38 CST 2015
     */
    public Date getDateCreated() {
        return dateCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tags.date_created
     *
     * @param dateCreated the value for tags.date_created
     * @mbggenerated Mon Mar 30 19:10:38 CST 2015
     */
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tags.last_updated
     *
     * @return the value of tags.last_updated
     * @mbggenerated Mon Mar 30 19:10:38 CST 2015
     */
    public Date getLastUpdated() {
        return lastUpdated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tags.last_updated
     *
     * @param lastUpdated the value for tags.last_updated
     * @mbggenerated Mon Mar 30 19:10:38 CST 2015
     */
    public void setLastUpdated(Date lastUpdated) {
        this.lastUpdated = lastUpdated;
    }
}