package com.welink.commons.persistence;

import com.welink.commons.domain.AnnouceDO;
import com.welink.commons.domain.AnnouceDOExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.springframework.stereotype.Repository;

@Repository
public interface AnnouceDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table annouce
     *
     * @mbggenerated Thu Nov 27 18:10:21 CST 2014
     */
    int countByExample(AnnouceDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table annouce
     *
     * @mbggenerated Thu Nov 27 18:10:21 CST 2014
     */
    int deleteByExample(AnnouceDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table annouce
     *
     * @mbggenerated Thu Nov 27 18:10:21 CST 2014
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table annouce
     *
     * @mbggenerated Thu Nov 27 18:10:21 CST 2014
     */
    int insert(AnnouceDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table annouce
     *
     * @mbggenerated Thu Nov 27 18:10:21 CST 2014
     */
    int insertSelective(AnnouceDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table annouce
     *
     * @mbggenerated Thu Nov 27 18:10:21 CST 2014
     */
    List<AnnouceDO> selectByExampleWithRowbounds(AnnouceDOExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table annouce
     *
     * @mbggenerated Thu Nov 27 18:10:21 CST 2014
     */
    List<AnnouceDO> selectByExample(AnnouceDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table annouce
     *
     * @mbggenerated Thu Nov 27 18:10:21 CST 2014
     */
    AnnouceDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table annouce
     *
     * @mbggenerated Thu Nov 27 18:10:21 CST 2014
     */
    int updateByExampleSelective(@Param("record") AnnouceDO record, @Param("example") AnnouceDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table annouce
     *
     * @mbggenerated Thu Nov 27 18:10:21 CST 2014
     */
    int updateByExample(@Param("record") AnnouceDO record, @Param("example") AnnouceDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table annouce
     *
     * @mbggenerated Thu Nov 27 18:10:21 CST 2014
     */
    int updateByPrimaryKeySelective(AnnouceDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table annouce
     *
     * @mbggenerated Thu Nov 27 18:10:21 CST 2014
     */
    int updateByPrimaryKey(AnnouceDO record);
}