package com.welink.commons.persistence;

import com.welink.commons.domain.BannerDO;
import com.welink.commons.domain.BannerDOExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.springframework.stereotype.Repository;

@Repository
public interface BannerDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table banner
     *
     * @mbggenerated Tue Nov 24 17:34:03 CST 2015
     */
    int countByExample(BannerDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table banner
     *
     * @mbggenerated Tue Nov 24 17:34:03 CST 2015
     */
    int deleteByExample(BannerDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table banner
     *
     * @mbggenerated Tue Nov 24 17:34:03 CST 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table banner
     *
     * @mbggenerated Tue Nov 24 17:34:03 CST 2015
     */
    int insert(BannerDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table banner
     *
     * @mbggenerated Tue Nov 24 17:34:03 CST 2015
     */
    int insertSelective(BannerDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table banner
     *
     * @mbggenerated Tue Nov 24 17:34:03 CST 2015
     */
    List<BannerDO> selectByExampleWithRowbounds(BannerDOExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table banner
     *
     * @mbggenerated Tue Nov 24 17:34:03 CST 2015
     */
    List<BannerDO> selectByExample(BannerDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table banner
     *
     * @mbggenerated Tue Nov 24 17:34:03 CST 2015
     */
    BannerDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table banner
     *
     * @mbggenerated Tue Nov 24 17:34:03 CST 2015
     */
    int updateByExampleSelective(@Param("record") BannerDO record, @Param("example") BannerDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table banner
     *
     * @mbggenerated Tue Nov 24 17:34:03 CST 2015
     */
    int updateByExample(@Param("record") BannerDO record, @Param("example") BannerDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table banner
     *
     * @mbggenerated Tue Nov 24 17:34:03 CST 2015
     */
    int updateByPrimaryKeySelective(BannerDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table banner
     *
     * @mbggenerated Tue Nov 24 17:34:03 CST 2015
     */
    int updateByPrimaryKey(BannerDO record);
}