package com.welink.commons.persistence;

import com.welink.commons.domain.ConfigureDO;
import com.welink.commons.domain.ConfigureDOExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.springframework.stereotype.Repository;

@Repository
public interface ConfigureDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table configure
     *
     * @mbggenerated Thu Nov 27 18:10:21 CST 2014
     */
    int countByExample(ConfigureDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table configure
     *
     * @mbggenerated Thu Nov 27 18:10:21 CST 2014
     */
    int deleteByExample(ConfigureDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table configure
     *
     * @mbggenerated Thu Nov 27 18:10:21 CST 2014
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table configure
     *
     * @mbggenerated Thu Nov 27 18:10:21 CST 2014
     */
    int insert(ConfigureDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table configure
     *
     * @mbggenerated Thu Nov 27 18:10:21 CST 2014
     */
    int insertSelective(ConfigureDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table configure
     *
     * @mbggenerated Thu Nov 27 18:10:21 CST 2014
     */
    List<ConfigureDO> selectByExampleWithRowbounds(ConfigureDOExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table configure
     *
     * @mbggenerated Thu Nov 27 18:10:21 CST 2014
     */
    List<ConfigureDO> selectByExample(ConfigureDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table configure
     *
     * @mbggenerated Thu Nov 27 18:10:21 CST 2014
     */
    ConfigureDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table configure
     *
     * @mbggenerated Thu Nov 27 18:10:21 CST 2014
     */
    int updateByExampleSelective(@Param("record") ConfigureDO record, @Param("example") ConfigureDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table configure
     *
     * @mbggenerated Thu Nov 27 18:10:21 CST 2014
     */
    int updateByExample(@Param("record") ConfigureDO record, @Param("example") ConfigureDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table configure
     *
     * @mbggenerated Thu Nov 27 18:10:21 CST 2014
     */
    int updateByPrimaryKeySelective(ConfigureDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table configure
     *
     * @mbggenerated Thu Nov 27 18:10:21 CST 2014
     */
    int updateByPrimaryKey(ConfigureDO record);
}