package com.welink.commons.persistence;

import com.welink.commons.domain.LinkCategory;
import com.welink.commons.domain.LinkCategoryExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.springframework.stereotype.Repository;

@Repository
public interface LinkCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table link_category
     *
     * @mbggenerated Thu Nov 27 18:10:21 CST 2014
     */
    int countByExample(LinkCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table link_category
     *
     * @mbggenerated Thu Nov 27 18:10:21 CST 2014
     */
    int deleteByExample(LinkCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table link_category
     *
     * @mbggenerated Thu Nov 27 18:10:21 CST 2014
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table link_category
     *
     * @mbggenerated Thu Nov 27 18:10:21 CST 2014
     */
    int insert(LinkCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table link_category
     *
     * @mbggenerated Thu Nov 27 18:10:21 CST 2014
     */
    int insertSelective(LinkCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table link_category
     *
     * @mbggenerated Thu Nov 27 18:10:21 CST 2014
     */
    List<LinkCategory> selectByExampleWithRowbounds(LinkCategoryExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table link_category
     *
     * @mbggenerated Thu Nov 27 18:10:21 CST 2014
     */
    List<LinkCategory> selectByExample(LinkCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table link_category
     *
     * @mbggenerated Thu Nov 27 18:10:21 CST 2014
     */
    LinkCategory selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table link_category
     *
     * @mbggenerated Thu Nov 27 18:10:21 CST 2014
     */
    int updateByExampleSelective(@Param("record") LinkCategory record, @Param("example") LinkCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table link_category
     *
     * @mbggenerated Thu Nov 27 18:10:21 CST 2014
     */
    int updateByExample(@Param("record") LinkCategory record, @Param("example") LinkCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table link_category
     *
     * @mbggenerated Thu Nov 27 18:10:21 CST 2014
     */
    int updateByPrimaryKeySelective(LinkCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table link_category
     *
     * @mbggenerated Thu Nov 27 18:10:21 CST 2014
     */
    int updateByPrimaryKey(LinkCategory record);
}