package com.welink.commons.persistence;

import com.welink.commons.domain.LinkReplyDO;
import com.welink.commons.domain.LinkReplyDOExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.springframework.stereotype.Repository;

@Repository
public interface LinkReplyDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table link_reply
     *
     * @mbggenerated Thu Nov 27 18:10:21 CST 2014
     */
    int countByExample(LinkReplyDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table link_reply
     *
     * @mbggenerated Thu Nov 27 18:10:21 CST 2014
     */
    int deleteByExample(LinkReplyDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table link_reply
     *
     * @mbggenerated Thu Nov 27 18:10:21 CST 2014
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table link_reply
     *
     * @mbggenerated Thu Nov 27 18:10:21 CST 2014
     */
    int insert(LinkReplyDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table link_reply
     *
     * @mbggenerated Thu Nov 27 18:10:21 CST 2014
     */
    int insertSelective(LinkReplyDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table link_reply
     *
     * @mbggenerated Thu Nov 27 18:10:21 CST 2014
     */
    List<LinkReplyDO> selectByExampleWithRowbounds(LinkReplyDOExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table link_reply
     *
     * @mbggenerated Thu Nov 27 18:10:21 CST 2014
     */
    List<LinkReplyDO> selectByExample(LinkReplyDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table link_reply
     *
     * @mbggenerated Thu Nov 27 18:10:21 CST 2014
     */
    LinkReplyDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table link_reply
     *
     * @mbggenerated Thu Nov 27 18:10:21 CST 2014
     */
    int updateByExampleSelective(@Param("record") LinkReplyDO record, @Param("example") LinkReplyDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table link_reply
     *
     * @mbggenerated Thu Nov 27 18:10:21 CST 2014
     */
    int updateByExample(@Param("record") LinkReplyDO record, @Param("example") LinkReplyDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table link_reply
     *
     * @mbggenerated Thu Nov 27 18:10:21 CST 2014
     */
    int updateByPrimaryKeySelective(LinkReplyDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table link_reply
     *
     * @mbggenerated Thu Nov 27 18:10:21 CST 2014
     */
    int updateByPrimaryKey(LinkReplyDO record);
}