package com.welink.commons.persistence;

import com.welink.commons.domain.LinkConversationDO;
import com.welink.commons.domain.LinkConversationDOExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.springframework.stereotype.Repository;

@Repository
public interface LinkConversationDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table link_conversation
     *
     * @mbggenerated Thu Nov 27 18:10:21 CST 2014
     */
    int countByExample(LinkConversationDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table link_conversation
     *
     * @mbggenerated Thu Nov 27 18:10:21 CST 2014
     */
    int deleteByExample(LinkConversationDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table link_conversation
     *
     * @mbggenerated Thu Nov 27 18:10:21 CST 2014
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table link_conversation
     *
     * @mbggenerated Thu Nov 27 18:10:21 CST 2014
     */
    int insert(LinkConversationDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table link_conversation
     *
     * @mbggenerated Thu Nov 27 18:10:21 CST 2014
     */
    int insertSelective(LinkConversationDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table link_conversation
     *
     * @mbggenerated Thu Nov 27 18:10:21 CST 2014
     */
    List<LinkConversationDO> selectByExampleWithRowbounds(LinkConversationDOExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table link_conversation
     *
     * @mbggenerated Thu Nov 27 18:10:21 CST 2014
     */
    List<LinkConversationDO> selectByExample(LinkConversationDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table link_conversation
     *
     * @mbggenerated Thu Nov 27 18:10:21 CST 2014
     */
    LinkConversationDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table link_conversation
     *
     * @mbggenerated Thu Nov 27 18:10:21 CST 2014
     */
    int updateByExampleSelective(@Param("record") LinkConversationDO record, @Param("example") LinkConversationDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table link_conversation
     *
     * @mbggenerated Thu Nov 27 18:10:21 CST 2014
     */
    int updateByExample(@Param("record") LinkConversationDO record, @Param("example") LinkConversationDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table link_conversation
     *
     * @mbggenerated Thu Nov 27 18:10:21 CST 2014
     */
    int updateByPrimaryKeySelective(LinkConversationDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table link_conversation
     *
     * @mbggenerated Thu Nov 27 18:10:21 CST 2014
     */
    int updateByPrimaryKey(LinkConversationDO record);
}