package com.welink.commons.persistence;

import com.welink.commons.domain.LogisticsDO;
import com.welink.commons.domain.LogisticsDOExample;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface LogisticsDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logistics
     *
     * @mbggenerated Fri Mar 20 11:44:21 CST 2015
     */
    int countByExample(LogisticsDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logistics
     *
     * @mbggenerated Fri Mar 20 11:44:21 CST 2015
     */
    int deleteByExample(LogisticsDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logistics
     *
     * @mbggenerated Fri Mar 20 11:44:21 CST 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logistics
     *
     * @mbggenerated Fri Mar 20 11:44:21 CST 2015
     */
    int insert(LogisticsDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logistics
     *
     * @mbggenerated Fri Mar 20 11:44:21 CST 2015
     */
    int insertSelective(LogisticsDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logistics
     *
     * @mbggenerated Fri Mar 20 11:44:21 CST 2015
     */
    List<LogisticsDO> selectByExample(LogisticsDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logistics
     *
     * @mbggenerated Fri Mar 20 11:44:21 CST 2015
     */
    LogisticsDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logistics
     *
     * @mbggenerated Fri Mar 20 11:44:21 CST 2015
     */
    int updateByExampleSelective(@Param("record") LogisticsDO record, @Param("example") LogisticsDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logistics
     *
     * @mbggenerated Fri Mar 20 11:44:21 CST 2015
     */
    int updateByExample(@Param("record") LogisticsDO record, @Param("example") LogisticsDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logistics
     *
     * @mbggenerated Fri Mar 20 11:44:21 CST 2015
     */
    int updateByPrimaryKeySelective(LogisticsDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logistics
     *
     * @mbggenerated Fri Mar 20 11:44:21 CST 2015
     */
    int updateByPrimaryKey(LogisticsDO record);
}