package com.welink.commons.persistence;

import com.welink.commons.domain.MessageSummaryDO;
import com.welink.commons.domain.MessageSummaryDOExample;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface MessageSummaryDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_summary
     *
     * @mbggenerated Fri Jun 05 11:51:18 CST 2015
     */
    int countByExample(MessageSummaryDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_summary
     *
     * @mbggenerated Fri Jun 05 11:51:18 CST 2015
     */
    int deleteByExample(MessageSummaryDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_summary
     *
     * @mbggenerated Fri Jun 05 11:51:18 CST 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_summary
     *
     * @mbggenerated Fri Jun 05 11:51:18 CST 2015
     */
    int insert(MessageSummaryDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_summary
     *
     * @mbggenerated Fri Jun 05 11:51:18 CST 2015
     */
    int insertSelective(MessageSummaryDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_summary
     *
     * @mbggenerated Fri Jun 05 11:51:18 CST 2015
     */
    List<MessageSummaryDO> selectByExampleWithRowbounds(MessageSummaryDOExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_summary
     *
     * @mbggenerated Fri Jun 05 11:51:18 CST 2015
     */
    List<MessageSummaryDO> selectByExample(MessageSummaryDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_summary
     *
     * @mbggenerated Fri Jun 05 11:51:18 CST 2015
     */
    MessageSummaryDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_summary
     *
     * @mbggenerated Fri Jun 05 11:51:18 CST 2015
     */
    int updateByExampleSelective(@Param("record") MessageSummaryDO record, @Param("example") MessageSummaryDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_summary
     *
     * @mbggenerated Fri Jun 05 11:51:18 CST 2015
     */
    int updateByExample(@Param("record") MessageSummaryDO record, @Param("example") MessageSummaryDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_summary
     *
     * @mbggenerated Fri Jun 05 11:51:18 CST 2015
     */
    int updateByPrimaryKeySelective(MessageSummaryDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_summary
     *
     * @mbggenerated Fri Jun 05 11:51:18 CST 2015
     */
    int updateByPrimaryKey(MessageSummaryDO record);
}