package com.welink.commons.persistence;

import com.welink.commons.domain.MikuMineCourseStepDO;
import com.welink.commons.domain.MikuMineCourseStepDOExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.springframework.stereotype.Repository;

@Repository
public interface MikuMineCourseStepDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miku_mine_course_step
     *
     * @mbggenerated Fri May 20 09:53:42 CST 2016
     */
    int countByExample(MikuMineCourseStepDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miku_mine_course_step
     *
     * @mbggenerated Fri May 20 09:53:42 CST 2016
     */
    int deleteByExample(MikuMineCourseStepDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miku_mine_course_step
     *
     * @mbggenerated Fri May 20 09:53:42 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miku_mine_course_step
     *
     * @mbggenerated Fri May 20 09:53:42 CST 2016
     */
    int insert(MikuMineCourseStepDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miku_mine_course_step
     *
     * @mbggenerated Fri May 20 09:53:42 CST 2016
     */
    int insertSelective(MikuMineCourseStepDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miku_mine_course_step
     *
     * @mbggenerated Fri May 20 09:53:42 CST 2016
     */
    List<MikuMineCourseStepDO> selectByExampleWithRowbounds(MikuMineCourseStepDOExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miku_mine_course_step
     *
     * @mbggenerated Fri May 20 09:53:42 CST 2016
     */
    List<MikuMineCourseStepDO> selectByExample(MikuMineCourseStepDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miku_mine_course_step
     *
     * @mbggenerated Fri May 20 09:53:42 CST 2016
     */
    MikuMineCourseStepDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miku_mine_course_step
     *
     * @mbggenerated Fri May 20 09:53:42 CST 2016
     */
    int updateByExampleSelective(@Param("record") MikuMineCourseStepDO record, @Param("example") MikuMineCourseStepDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miku_mine_course_step
     *
     * @mbggenerated Fri May 20 09:53:42 CST 2016
     */
    int updateByExample(@Param("record") MikuMineCourseStepDO record, @Param("example") MikuMineCourseStepDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miku_mine_course_step
     *
     * @mbggenerated Fri May 20 09:53:42 CST 2016
     */
    int updateByPrimaryKeySelective(MikuMineCourseStepDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miku_mine_course_step
     *
     * @mbggenerated Fri May 20 09:53:42 CST 2016
     */
    int updateByPrimaryKey(MikuMineCourseStepDO record);
}