package com.welink.commons.persistence;

import com.welink.commons.domain.MikuShareGetpayDO;
import com.welink.commons.domain.MikuShareGetpayDOExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.springframework.stereotype.Repository;

@Repository
public interface MikuShareGetpayDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miku_share_getpay
     *
     * @mbggenerated Mon Dec 07 14:29:47 CST 2015
     */
    int countByExample(MikuShareGetpayDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miku_share_getpay
     *
     * @mbggenerated Mon Dec 07 14:29:47 CST 2015
     */
    int deleteByExample(MikuShareGetpayDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miku_share_getpay
     *
     * @mbggenerated Mon Dec 07 14:29:47 CST 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miku_share_getpay
     *
     * @mbggenerated Mon Dec 07 14:29:47 CST 2015
     */
    int insert(MikuShareGetpayDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miku_share_getpay
     *
     * @mbggenerated Mon Dec 07 14:29:47 CST 2015
     */
    int insertSelective(MikuShareGetpayDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miku_share_getpay
     *
     * @mbggenerated Mon Dec 07 14:29:47 CST 2015
     */
    List<MikuShareGetpayDO> selectByExampleWithRowbounds(MikuShareGetpayDOExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miku_share_getpay
     *
     * @mbggenerated Mon Dec 07 14:29:47 CST 2015
     */
    List<MikuShareGetpayDO> selectByExample(MikuShareGetpayDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miku_share_getpay
     *
     * @mbggenerated Mon Dec 07 14:29:47 CST 2015
     */
    MikuShareGetpayDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miku_share_getpay
     *
     * @mbggenerated Mon Dec 07 14:29:47 CST 2015
     */
    int updateByExampleSelective(@Param("record") MikuShareGetpayDO record, @Param("example") MikuShareGetpayDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miku_share_getpay
     *
     * @mbggenerated Mon Dec 07 14:29:47 CST 2015
     */
    int updateByExample(@Param("record") MikuShareGetpayDO record, @Param("example") MikuShareGetpayDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miku_share_getpay
     *
     * @mbggenerated Mon Dec 07 14:29:47 CST 2015
     */
    int updateByPrimaryKeySelective(MikuShareGetpayDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miku_share_getpay
     *
     * @mbggenerated Mon Dec 07 14:29:47 CST 2015
     */
    int updateByPrimaryKey(MikuShareGetpayDO record);
}