package com.welink.commons.persistence;

import com.welink.commons.domain.MikuItemShareParaDO;
import com.welink.commons.domain.MikuItemShareParaDOExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.springframework.stereotype.Repository;

@Repository
public interface MikuItemShareParaDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miku_item_share_para
     *
     * @mbggenerated Wed Nov 04 14:57:35 CST 2015
     */
    int countByExample(MikuItemShareParaDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miku_item_share_para
     *
     * @mbggenerated Wed Nov 04 14:57:35 CST 2015
     */
    int deleteByExample(MikuItemShareParaDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miku_item_share_para
     *
     * @mbggenerated Wed Nov 04 14:57:35 CST 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miku_item_share_para
     *
     * @mbggenerated Wed Nov 04 14:57:35 CST 2015
     */
    int insert(MikuItemShareParaDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miku_item_share_para
     *
     * @mbggenerated Wed Nov 04 14:57:35 CST 2015
     */
    int insertSelective(MikuItemShareParaDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miku_item_share_para
     *
     * @mbggenerated Wed Nov 04 14:57:35 CST 2015
     */
    List<MikuItemShareParaDO> selectByExampleWithRowbounds(MikuItemShareParaDOExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miku_item_share_para
     *
     * @mbggenerated Wed Nov 04 14:57:35 CST 2015
     */
    List<MikuItemShareParaDO> selectByExample(MikuItemShareParaDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miku_item_share_para
     *
     * @mbggenerated Wed Nov 04 14:57:35 CST 2015
     */
    MikuItemShareParaDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miku_item_share_para
     *
     * @mbggenerated Wed Nov 04 14:57:35 CST 2015
     */
    int updateByExampleSelective(@Param("record") MikuItemShareParaDO record, @Param("example") MikuItemShareParaDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miku_item_share_para
     *
     * @mbggenerated Wed Nov 04 14:57:35 CST 2015
     */
    int updateByExample(@Param("record") MikuItemShareParaDO record, @Param("example") MikuItemShareParaDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miku_item_share_para
     *
     * @mbggenerated Wed Nov 04 14:57:35 CST 2015
     */
    int updateByPrimaryKeySelective(MikuItemShareParaDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miku_item_share_para
     *
     * @mbggenerated Wed Nov 04 14:57:35 CST 2015
     */
    int updateByPrimaryKey(MikuItemShareParaDO record);
}