package com.welink.commons.persistence;

import com.welink.commons.domain.MikuCsadEvaluateDO;
import com.welink.commons.domain.MikuCsadEvaluateDOExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.springframework.stereotype.Repository;

@Repository
public interface MikuCsadEvaluateDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miku_csad_evaluate
     *
     * @mbggenerated Wed Apr 20 16:18:39 CST 2016
     */
    int countByExample(MikuCsadEvaluateDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miku_csad_evaluate
     *
     * @mbggenerated Wed Apr 20 16:18:39 CST 2016
     */
    int deleteByExample(MikuCsadEvaluateDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miku_csad_evaluate
     *
     * @mbggenerated Wed Apr 20 16:18:39 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miku_csad_evaluate
     *
     * @mbggenerated Wed Apr 20 16:18:39 CST 2016
     */
    int insert(MikuCsadEvaluateDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miku_csad_evaluate
     *
     * @mbggenerated Wed Apr 20 16:18:39 CST 2016
     */
    int insertSelective(MikuCsadEvaluateDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miku_csad_evaluate
     *
     * @mbggenerated Wed Apr 20 16:18:39 CST 2016
     */
    List<MikuCsadEvaluateDO> selectByExampleWithRowbounds(MikuCsadEvaluateDOExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miku_csad_evaluate
     *
     * @mbggenerated Wed Apr 20 16:18:39 CST 2016
     */
    List<MikuCsadEvaluateDO> selectByExample(MikuCsadEvaluateDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miku_csad_evaluate
     *
     * @mbggenerated Wed Apr 20 16:18:39 CST 2016
     */
    MikuCsadEvaluateDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miku_csad_evaluate
     *
     * @mbggenerated Wed Apr 20 16:18:39 CST 2016
     */
    int updateByExampleSelective(@Param("record") MikuCsadEvaluateDO record, @Param("example") MikuCsadEvaluateDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miku_csad_evaluate
     *
     * @mbggenerated Wed Apr 20 16:18:39 CST 2016
     */
    int updateByExample(@Param("record") MikuCsadEvaluateDO record, @Param("example") MikuCsadEvaluateDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miku_csad_evaluate
     *
     * @mbggenerated Wed Apr 20 16:18:39 CST 2016
     */
    int updateByPrimaryKeySelective(MikuCsadEvaluateDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miku_csad_evaluate
     *
     * @mbggenerated Wed Apr 20 16:18:39 CST 2016
     */
    int updateByPrimaryKey(MikuCsadEvaluateDO record);
}