package com.welink.commons.persistence;

import com.welink.commons.domain.MikuScratchCardDO;
import com.welink.commons.domain.MikuScratchCardDOExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.springframework.stereotype.Repository;

@Repository
public interface MikuScratchCardDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miku_scratch_card
     *
     * @mbggenerated Tue Apr 05 19:42:01 CST 2016
     */
    int countByExample(MikuScratchCardDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miku_scratch_card
     *
     * @mbggenerated Tue Apr 05 19:42:01 CST 2016
     */
    int deleteByExample(MikuScratchCardDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miku_scratch_card
     *
     * @mbggenerated Tue Apr 05 19:42:01 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miku_scratch_card
     *
     * @mbggenerated Tue Apr 05 19:42:01 CST 2016
     */
    int insert(MikuScratchCardDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miku_scratch_card
     *
     * @mbggenerated Tue Apr 05 19:42:01 CST 2016
     */
    int insertSelective(MikuScratchCardDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miku_scratch_card
     *
     * @mbggenerated Tue Apr 05 19:42:01 CST 2016
     */
    List<MikuScratchCardDO> selectByExampleWithRowbounds(MikuScratchCardDOExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miku_scratch_card
     *
     * @mbggenerated Tue Apr 05 19:42:01 CST 2016
     */
    List<MikuScratchCardDO> selectByExample(MikuScratchCardDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miku_scratch_card
     *
     * @mbggenerated Tue Apr 05 19:42:01 CST 2016
     */
    MikuScratchCardDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miku_scratch_card
     *
     * @mbggenerated Tue Apr 05 19:42:01 CST 2016
     */
    int updateByExampleSelective(@Param("record") MikuScratchCardDO record, @Param("example") MikuScratchCardDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miku_scratch_card
     *
     * @mbggenerated Tue Apr 05 19:42:01 CST 2016
     */
    int updateByExample(@Param("record") MikuScratchCardDO record, @Param("example") MikuScratchCardDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miku_scratch_card
     *
     * @mbggenerated Tue Apr 05 19:42:01 CST 2016
     */
    int updateByPrimaryKeySelective(MikuScratchCardDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miku_scratch_card
     *
     * @mbggenerated Tue Apr 05 19:42:01 CST 2016
     */
    int updateByPrimaryKey(MikuScratchCardDO record);
}