package com.welink.commons.persistence;

import com.welink.commons.domain.MikuCsadServiceLogDO;
import com.welink.commons.domain.MikuCsadServiceLogDOExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.springframework.stereotype.Repository;

@Repository
public interface MikuCsadServiceLogDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miku_csad_service_log
     *
     * @mbggenerated Thu Apr 28 09:39:17 CST 2016
     */
    int countByExample(MikuCsadServiceLogDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miku_csad_service_log
     *
     * @mbggenerated Thu Apr 28 09:39:17 CST 2016
     */
    int deleteByExample(MikuCsadServiceLogDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miku_csad_service_log
     *
     * @mbggenerated Thu Apr 28 09:39:17 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miku_csad_service_log
     *
     * @mbggenerated Thu Apr 28 09:39:17 CST 2016
     */
    int insert(MikuCsadServiceLogDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miku_csad_service_log
     *
     * @mbggenerated Thu Apr 28 09:39:17 CST 2016
     */
    int insertSelective(MikuCsadServiceLogDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miku_csad_service_log
     *
     * @mbggenerated Thu Apr 28 09:39:17 CST 2016
     */
    List<MikuCsadServiceLogDO> selectByExampleWithRowbounds(MikuCsadServiceLogDOExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miku_csad_service_log
     *
     * @mbggenerated Thu Apr 28 09:39:17 CST 2016
     */
    List<MikuCsadServiceLogDO> selectByExample(MikuCsadServiceLogDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miku_csad_service_log
     *
     * @mbggenerated Thu Apr 28 09:39:17 CST 2016
     */
    MikuCsadServiceLogDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miku_csad_service_log
     *
     * @mbggenerated Thu Apr 28 09:39:17 CST 2016
     */
    int updateByExampleSelective(@Param("record") MikuCsadServiceLogDO record, @Param("example") MikuCsadServiceLogDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miku_csad_service_log
     *
     * @mbggenerated Thu Apr 28 09:39:17 CST 2016
     */
    int updateByExample(@Param("record") MikuCsadServiceLogDO record, @Param("example") MikuCsadServiceLogDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miku_csad_service_log
     *
     * @mbggenerated Thu Apr 28 09:39:17 CST 2016
     */
    int updateByPrimaryKeySelective(MikuCsadServiceLogDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miku_csad_service_log
     *
     * @mbggenerated Thu Apr 28 09:39:17 CST 2016
     */
    int updateByPrimaryKey(MikuCsadServiceLogDO record);
}