package com.welink.commons.persistence;

import com.welink.commons.domain.MikuWalletOriginDO;
import com.welink.commons.domain.MikuWalletOriginDOExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.springframework.stereotype.Repository;

@Repository
public interface MikuWalletOriginDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miku_wallet_origin
     *
     * @mbggenerated Sat Feb 27 15:50:06 CST 2016
     */
    int countByExample(MikuWalletOriginDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miku_wallet_origin
     *
     * @mbggenerated Sat Feb 27 15:50:06 CST 2016
     */
    int deleteByExample(MikuWalletOriginDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miku_wallet_origin
     *
     * @mbggenerated Sat Feb 27 15:50:06 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miku_wallet_origin
     *
     * @mbggenerated Sat Feb 27 15:50:06 CST 2016
     */
    int insert(MikuWalletOriginDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miku_wallet_origin
     *
     * @mbggenerated Sat Feb 27 15:50:06 CST 2016
     */
    int insertSelective(MikuWalletOriginDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miku_wallet_origin
     *
     * @mbggenerated Sat Feb 27 15:50:06 CST 2016
     */
    List<MikuWalletOriginDO> selectByExampleWithRowbounds(MikuWalletOriginDOExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miku_wallet_origin
     *
     * @mbggenerated Sat Feb 27 15:50:06 CST 2016
     */
    List<MikuWalletOriginDO> selectByExample(MikuWalletOriginDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miku_wallet_origin
     *
     * @mbggenerated Sat Feb 27 15:50:06 CST 2016
     */
    MikuWalletOriginDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miku_wallet_origin
     *
     * @mbggenerated Sat Feb 27 15:50:06 CST 2016
     */
    int updateByExampleSelective(@Param("record") MikuWalletOriginDO record, @Param("example") MikuWalletOriginDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miku_wallet_origin
     *
     * @mbggenerated Sat Feb 27 15:50:06 CST 2016
     */
    int updateByExample(@Param("record") MikuWalletOriginDO record, @Param("example") MikuWalletOriginDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miku_wallet_origin
     *
     * @mbggenerated Sat Feb 27 15:50:06 CST 2016
     */
    int updateByPrimaryKeySelective(MikuWalletOriginDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miku_wallet_origin
     *
     * @mbggenerated Sat Feb 27 15:50:06 CST 2016
     */
    int updateByPrimaryKey(MikuWalletOriginDO record);
}