package com.welink.commons.persistence;

import com.welink.commons.domain.MikuOrdersLogisticsDO;
import com.welink.commons.domain.MikuOrdersLogisticsDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.springframework.stereotype.Repository;
@Repository
public interface MikuOrdersLogisticsDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miku_orders_logistics
     *
     * @mbggenerated Thu Mar 31 16:58:19 CST 2016
     */
    int countByExample(MikuOrdersLogisticsDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miku_orders_logistics
     *
     * @mbggenerated Thu Mar 31 16:58:19 CST 2016
     */
    int deleteByExample(MikuOrdersLogisticsDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miku_orders_logistics
     *
     * @mbggenerated Thu Mar 31 16:58:19 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miku_orders_logistics
     *
     * @mbggenerated Thu Mar 31 16:58:19 CST 2016
     */
    int insert(MikuOrdersLogisticsDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miku_orders_logistics
     *
     * @mbggenerated Thu Mar 31 16:58:19 CST 2016
     */
    int insertSelective(MikuOrdersLogisticsDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miku_orders_logistics
     *
     * @mbggenerated Thu Mar 31 16:58:19 CST 2016
     */
    List<MikuOrdersLogisticsDO> selectByExampleWithBLOBsWithRowbounds(MikuOrdersLogisticsDOExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miku_orders_logistics
     *
     * @mbggenerated Thu Mar 31 16:58:19 CST 2016
     */
    List<MikuOrdersLogisticsDO> selectByExampleWithBLOBs(MikuOrdersLogisticsDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miku_orders_logistics
     *
     * @mbggenerated Thu Mar 31 16:58:19 CST 2016
     */
    List<MikuOrdersLogisticsDO> selectByExampleWithRowbounds(MikuOrdersLogisticsDOExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miku_orders_logistics
     *
     * @mbggenerated Thu Mar 31 16:58:19 CST 2016
     */
    List<MikuOrdersLogisticsDO> selectByExample(MikuOrdersLogisticsDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miku_orders_logistics
     *
     * @mbggenerated Thu Mar 31 16:58:19 CST 2016
     */
    MikuOrdersLogisticsDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miku_orders_logistics
     *
     * @mbggenerated Thu Mar 31 16:58:19 CST 2016
     */
    int updateByExampleSelective(@Param("record") MikuOrdersLogisticsDO record, @Param("example") MikuOrdersLogisticsDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miku_orders_logistics
     *
     * @mbggenerated Thu Mar 31 16:58:19 CST 2016
     */
    int updateByExampleWithBLOBs(@Param("record") MikuOrdersLogisticsDO record, @Param("example") MikuOrdersLogisticsDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miku_orders_logistics
     *
     * @mbggenerated Thu Mar 31 16:58:19 CST 2016
     */
    int updateByExample(@Param("record") MikuOrdersLogisticsDO record, @Param("example") MikuOrdersLogisticsDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miku_orders_logistics
     *
     * @mbggenerated Thu Mar 31 16:58:19 CST 2016
     */
    int updateByPrimaryKeySelective(MikuOrdersLogisticsDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miku_orders_logistics
     *
     * @mbggenerated Thu Mar 31 16:58:19 CST 2016
     */
    int updateByPrimaryKeyWithBLOBs(MikuOrdersLogisticsDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miku_orders_logistics
     *
     * @mbggenerated Thu Mar 31 16:58:19 CST 2016
     */
    int updateByPrimaryKey(MikuOrdersLogisticsDO record);
}