package com.welink.commons.persistence;

import com.welink.commons.domain.MikuSalesRecordDO;
import com.welink.commons.domain.MikuSalesRecordDOExample;
import com.welink.commons.domain.Order;
import com.welink.commons.vo.MikuReturnGoodsVO;
import com.welink.commons.vo.MikuSalesRecordVO;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.springframework.stereotype.Repository;

@Repository
public interface MikuSalesRecordDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miku_sales_record
     *
     * @mbggenerated Mon Dec 07 14:29:47 CST 2015
     */
    int countByExample(MikuSalesRecordDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miku_sales_record
     *
     * @mbggenerated Mon Dec 07 14:29:47 CST 2015
     */
    int deleteByExample(MikuSalesRecordDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miku_sales_record
     *
     * @mbggenerated Mon Dec 07 14:29:47 CST 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miku_sales_record
     *
     * @mbggenerated Mon Dec 07 14:29:47 CST 2015
     */
    int insert(MikuSalesRecordDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miku_sales_record
     *
     * @mbggenerated Mon Dec 07 14:29:47 CST 2015
     */
    int insertSelective(MikuSalesRecordDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miku_sales_record
     *
     * @mbggenerated Mon Dec 07 14:29:47 CST 2015
     */
    List<MikuSalesRecordDO> selectByExampleWithRowbounds(MikuSalesRecordDOExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miku_sales_record
     *
     * @mbggenerated Mon Dec 07 14:29:47 CST 2015
     */
    List<MikuSalesRecordDO> selectByExample(MikuSalesRecordDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miku_sales_record
     *
     * @mbggenerated Mon Dec 07 14:29:47 CST 2015
     */
    MikuSalesRecordDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miku_sales_record
     *
     * @mbggenerated Mon Dec 07 14:29:47 CST 2015
     */
    int updateByExampleSelective(@Param("record") MikuSalesRecordDO record, @Param("example") MikuSalesRecordDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miku_sales_record
     *
     * @mbggenerated Mon Dec 07 14:29:47 CST 2015
     */
    int updateByExample(@Param("record") MikuSalesRecordDO record, @Param("example") MikuSalesRecordDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miku_sales_record
     *
     * @mbggenerated Mon Dec 07 14:29:47 CST 2015
     */
    int updateByPrimaryKeySelective(MikuSalesRecordDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miku_sales_record
     *
     * @mbggenerated Mon Dec 07 14:29:47 CST 2015
     */
    int updateByPrimaryKey(MikuSalesRecordDO record);
    
    List<MikuSalesRecordDO> selectGroupTradeByExample(MikuSalesRecordDOExample example);
    
    List<MikuSalesRecordDO> selectShareGetpay(Map<String,Object> map);
    
    List<MikuSalesRecordDO> selectSalesRecordList(Map<String,Object> map);
    
    List<MikuSalesRecordVO> selectSalesRecordVOList(Map<String,Object> map);
    
    List<MikuSalesRecordVO> selectSalesRecordGroupByTradeList(Map<String,Object> map);
    
    /**
     * 
     * selectReturnProfitOrderList:(<!-- 查找需退分润的订单列表 -->). <br/>
     *
     * @author LuoGuangChun
     * @return
     */
    List<Order> selectReturnProfitOrderList();
    
    /**
     * 
     * getReturnSaleRecordVOList:(查询退货列表). <br/>
     * TODO(这里描述这个方法适用条件 – 可选).<br/>
     *
     * @author LuoGuangChun
     * @param map
     */
    List<MikuSalesRecordVO> getReturnSaleRecordVOList(Map<String,Object> map);
    
    /**
     * 
     * sumReturnSaleRecord:(统计退货分润金额). <br/>
     * TODO(这里描述这个方法适用条件 – 可选).<br/>
     *
     * @author LuoGuangChun
     * @param map
     * @return
     */
    Long sumReturnSaleRecord(Map<String,Object> map);
    
}