package com.welink.commons.persistence;

import com.welink.commons.domain.MikuCrowdfundDetailDO;
import com.welink.commons.domain.MikuCrowdfundDetailDOExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.springframework.stereotype.Repository;

@Repository
public interface MikuCrowdfundDetailDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miku_crowdfund_detail
     *
     * @mbggenerated Mon Feb 15 15:58:29 CST 2016
     */
    int countByExample(MikuCrowdfundDetailDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miku_crowdfund_detail
     *
     * @mbggenerated Mon Feb 15 15:58:29 CST 2016
     */
    int deleteByExample(MikuCrowdfundDetailDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miku_crowdfund_detail
     *
     * @mbggenerated Mon Feb 15 15:58:29 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miku_crowdfund_detail
     *
     * @mbggenerated Mon Feb 15 15:58:29 CST 2016
     */
    int insert(MikuCrowdfundDetailDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miku_crowdfund_detail
     *
     * @mbggenerated Mon Feb 15 15:58:29 CST 2016
     */
    int insertSelective(MikuCrowdfundDetailDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miku_crowdfund_detail
     *
     * @mbggenerated Mon Feb 15 15:58:29 CST 2016
     */
    List<MikuCrowdfundDetailDO> selectByExampleWithRowbounds(MikuCrowdfundDetailDOExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miku_crowdfund_detail
     *
     * @mbggenerated Mon Feb 15 15:58:29 CST 2016
     */
    List<MikuCrowdfundDetailDO> selectByExample(MikuCrowdfundDetailDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miku_crowdfund_detail
     *
     * @mbggenerated Mon Feb 15 15:58:29 CST 2016
     */
    MikuCrowdfundDetailDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miku_crowdfund_detail
     *
     * @mbggenerated Mon Feb 15 15:58:29 CST 2016
     */
    int updateByExampleSelective(@Param("record") MikuCrowdfundDetailDO record, @Param("example") MikuCrowdfundDetailDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miku_crowdfund_detail
     *
     * @mbggenerated Mon Feb 15 15:58:29 CST 2016
     */
    int updateByExample(@Param("record") MikuCrowdfundDetailDO record, @Param("example") MikuCrowdfundDetailDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miku_crowdfund_detail
     *
     * @mbggenerated Mon Feb 15 15:58:29 CST 2016
     */
    int updateByPrimaryKeySelective(MikuCrowdfundDetailDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miku_crowdfund_detail
     *
     * @mbggenerated Mon Feb 15 15:58:29 CST 2016
     */
    int updateByPrimaryKey(MikuCrowdfundDetailDO record);
}