package com.welink.commons.persistence;

import com.welink.commons.domain.MikuSensitiveWordsDO;
import com.welink.commons.domain.MikuSensitiveWordsDOExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.springframework.stereotype.Repository;

@Repository
public interface MikuSensitiveWordsDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miku_sensitive_words
     *
     * @mbggenerated Fri Jan 08 09:40:27 CST 2016
     */
    int countByExample(MikuSensitiveWordsDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miku_sensitive_words
     *
     * @mbggenerated Fri Jan 08 09:40:27 CST 2016
     */
    int deleteByExample(MikuSensitiveWordsDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miku_sensitive_words
     *
     * @mbggenerated Fri Jan 08 09:40:27 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miku_sensitive_words
     *
     * @mbggenerated Fri Jan 08 09:40:27 CST 2016
     */
    int insert(MikuSensitiveWordsDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miku_sensitive_words
     *
     * @mbggenerated Fri Jan 08 09:40:27 CST 2016
     */
    int insertSelective(MikuSensitiveWordsDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miku_sensitive_words
     *
     * @mbggenerated Fri Jan 08 09:40:27 CST 2016
     */
    List<MikuSensitiveWordsDO> selectByExampleWithRowbounds(MikuSensitiveWordsDOExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miku_sensitive_words
     *
     * @mbggenerated Fri Jan 08 09:40:27 CST 2016
     */
    List<MikuSensitiveWordsDO> selectByExample(MikuSensitiveWordsDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miku_sensitive_words
     *
     * @mbggenerated Fri Jan 08 09:40:27 CST 2016
     */
    MikuSensitiveWordsDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miku_sensitive_words
     *
     * @mbggenerated Fri Jan 08 09:40:27 CST 2016
     */
    int updateByExampleSelective(@Param("record") MikuSensitiveWordsDO record, @Param("example") MikuSensitiveWordsDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miku_sensitive_words
     *
     * @mbggenerated Fri Jan 08 09:40:27 CST 2016
     */
    int updateByExample(@Param("record") MikuSensitiveWordsDO record, @Param("example") MikuSensitiveWordsDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miku_sensitive_words
     *
     * @mbggenerated Fri Jan 08 09:40:27 CST 2016
     */
    int updateByPrimaryKeySelective(MikuSensitiveWordsDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miku_sensitive_words
     *
     * @mbggenerated Fri Jan 08 09:40:27 CST 2016
     */
    int updateByPrimaryKey(MikuSensitiveWordsDO record);
}