package com.welink.commons.persistence;

import com.welink.commons.domain.PointAccountDO;
import com.welink.commons.domain.PointAccountDOExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface PointAccountDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table point_account
     *
     * @mbggenerated Mon Mar 09 15:35:12 CST 2015
     */
    int countByExample(PointAccountDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table point_account
     *
     * @mbggenerated Mon Mar 09 15:35:12 CST 2015
     */
    int deleteByExample(PointAccountDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table point_account
     *
     * @mbggenerated Mon Mar 09 15:35:12 CST 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table point_account
     *
     * @mbggenerated Mon Mar 09 15:35:12 CST 2015
     */
    int insert(PointAccountDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table point_account
     *
     * @mbggenerated Mon Mar 09 15:35:12 CST 2015
     */
    int insertSelective(PointAccountDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table point_account
     *
     * @mbggenerated Mon Mar 09 15:35:12 CST 2015
     */
    List<PointAccountDO> selectByExample(PointAccountDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table point_account
     *
     * @mbggenerated Mon Mar 09 15:35:12 CST 2015
     */
    PointAccountDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table point_account
     *
     * @mbggenerated Mon Mar 09 15:35:12 CST 2015
     */
    int updateByExampleSelective(@Param("record") PointAccountDO record, @Param("example") PointAccountDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table point_account
     *
     * @mbggenerated Mon Mar 09 15:35:12 CST 2015
     */
    int updateByExample(@Param("record") PointAccountDO record, @Param("example") PointAccountDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table point_account
     *
     * @mbggenerated Mon Mar 09 15:35:12 CST 2015
     */
    int updateByPrimaryKeySelective(PointAccountDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table point_account
     *
     * @mbggenerated Mon Mar 09 15:35:12 CST 2015
     */
    int updateByPrimaryKey(PointAccountDO record);
}