package com.welink.commons.persistence;

import com.welink.commons.domain.ShopDO;
import com.welink.commons.domain.ShopDOExample;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface ShopDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbggenerated Wed Apr 15 10:11:24 CST 2015
     */
    int countByExample(ShopDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbggenerated Wed Apr 15 10:11:24 CST 2015
     */
    int deleteByExample(ShopDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbggenerated Wed Apr 15 10:11:24 CST 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbggenerated Wed Apr 15 10:11:24 CST 2015
     */
    int insert(ShopDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbggenerated Wed Apr 15 10:11:24 CST 2015
     */
    int insertSelective(ShopDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbggenerated Wed Apr 15 10:11:24 CST 2015
     */
    List<ShopDO> selectByExample(ShopDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbggenerated Wed Apr 15 10:11:24 CST 2015
     */
    ShopDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbggenerated Wed Apr 15 10:11:24 CST 2015
     */
    int updateByExampleSelective(@Param("record") ShopDO record, @Param("example") ShopDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbggenerated Wed Apr 15 10:11:24 CST 2015
     */
    int updateByExample(@Param("record") ShopDO record, @Param("example") ShopDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbggenerated Wed Apr 15 10:11:24 CST 2015
     */
    int updateByPrimaryKeySelective(ShopDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbggenerated Wed Apr 15 10:11:24 CST 2015
     */
    int updateByPrimaryKey(ShopDO record);
}