package com.welink.commons.persistence;

import com.welink.commons.domain.TransCheckDO;
import com.welink.commons.domain.TransCheckDOExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.springframework.stereotype.Repository;

@Repository
public interface TransCheckDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trans_check
     *
     * @mbggenerated Thu Nov 27 18:10:21 CST 2014
     */
    int countByExample(TransCheckDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trans_check
     *
     * @mbggenerated Thu Nov 27 18:10:21 CST 2014
     */
    int deleteByExample(TransCheckDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trans_check
     *
     * @mbggenerated Thu Nov 27 18:10:21 CST 2014
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trans_check
     *
     * @mbggenerated Thu Nov 27 18:10:21 CST 2014
     */
    int insert(TransCheckDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trans_check
     *
     * @mbggenerated Thu Nov 27 18:10:21 CST 2014
     */
    int insertSelective(TransCheckDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trans_check
     *
     * @mbggenerated Thu Nov 27 18:10:21 CST 2014
     */
    List<TransCheckDO> selectByExampleWithRowbounds(TransCheckDOExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trans_check
     *
     * @mbggenerated Thu Nov 27 18:10:21 CST 2014
     */
    List<TransCheckDO> selectByExample(TransCheckDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trans_check
     *
     * @mbggenerated Thu Nov 27 18:10:21 CST 2014
     */
    TransCheckDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trans_check
     *
     * @mbggenerated Thu Nov 27 18:10:21 CST 2014
     */
    int updateByExampleSelective(@Param("record") TransCheckDO record, @Param("example") TransCheckDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trans_check
     *
     * @mbggenerated Thu Nov 27 18:10:21 CST 2014
     */
    int updateByExample(@Param("record") TransCheckDO record, @Param("example") TransCheckDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trans_check
     *
     * @mbggenerated Thu Nov 27 18:10:21 CST 2014
     */
    int updateByPrimaryKeySelective(TransCheckDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trans_check
     *
     * @mbggenerated Thu Nov 27 18:10:21 CST 2014
     */
    int updateByPrimaryKey(TransCheckDO record);
}